dynawo/dynawo

util/autocompletion/deploy_autocompletion.sh
because it is not portable outside of Linux.
=> #149 Replaced getopt in deploy autocompletion 

dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/NodeFault.xml
Add a preassembled model to do short circuit on nodes.
The non regression test associated will be pushed with newer IEEE14 test cases
=> #164 Add a preassembled model for node fault

dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
Now PhaseTapchangers delay times are deternmined after network parameters TFO_t1st_HT, TFO_t1st_THT, TFO_tNext_HT, TFO_tNext_THT, as it is for ratioTapChangers.
=> #271 delay times as parameters for PhaseTapChangers

dynawo/sources/Modeler/DataInterface/DYNGeneratorInterfaceIIDM.cpp
Currently, when there is a reactiveCapabilityCurve, the point with the largest QMax and the point with the lowest QMin are taken.
This issue aims at updating the getQMax and getQMin functions so that the actual value on the curve/line is taken depending on the operating point.
=> #911 Update getQMax and getQMin

dynawo/sources/Modeler/DataInterface/DYNDataInterfaceIIDM.cpp
There were plenty of ways to implement the test, such as first searching in a new and separate method the interfaces and test before creating the interface object that they are identical.
Finally I have chosen to do a very simple modification using the existing methods because it is the less invasive approach (at this stage, I only do it for node breaker topology) and the simplest to understand. I think there is no impact on performance and no gain to expect from another implementation.
=> #1000 Dealing with bad topology structure

dynawo/sources/Models/CPP/ModelNetwork/DYNModelPhaseTapChanger.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelPhaseTapChanger.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelRatioTapChanger.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelRatioTapChanger.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTapChanger.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/TestTapChanger.cpp
Last version of code revision: turning std::map into a std::vector in the CPP Model: TapChanger
=> #873 873 turning std::map in std::vector in CCP TapChanger Model

dynawo/sources/Models/Modelica/Dynawo/Connectors/ACPower.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/GeneratorPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/GeneratorPV.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPV.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVProp.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Transformers/BaseClasses.mo
* Cosmetic improvements:
Modify the background color for terminal.
Add missing icons
Modifications on the order of parameters in Base Transformers to have the same one as in Line
* Functional improvements:
Correction of an issue in Machines BaseClasses: the variables and parameters used in a partial model should be declared into this partial model and not another (except if the second one extends the first one)
Correction on the use of pre in Machines Signal N BaseClasses: pre() can only be applied on discrete values
=> #1063 Library improvements for Modelica use

dynawo/sources/Models/CPP/ModelVariationArea/DYNModelVariationArea.cpp, dynawo/sources/Models/CPP/ModelVariationArea/DYNModelVariationArea.h, dynawo/sources/Models/CPP/ModelVariationArea/test/TestVariationArea.cpp
@thiebarrrte fyi we will then after this development require a deltaP and a deltaQ parameter for each load connected to the variation area. The parameter syntax is similar to the one adopted for the OmegaRef model, ie deltaP_load_0 to deltaP_load_nbLoads-1 and the same for deltaQ.
=> 1084 parameters

dynawo/sources/Common/DYNTrace.cpp, dynawo/sources/Common/DYNTrace.h, dynawo/sources/Common/DYNTraceStream.cpp
All info logs will be built in the stream to be displayed,
at least, on standard output
=> #1100 Correct traces on standard output

dynawo/sources/Solvers/SolverSIM/DYNSolverSIM.cpp
This g copy is completely useless except in debug mode because g0 is not used in the evalZMode method and is anyway updated at the end of it for the next time step.
=> #1413 Remove useless copy of g

documentation/functionalDoc/functionalDoc.tex, dynawo/sources/Common/Dictionaries/DYNError_en_GB.dic, dynawo/sources/Modeler/util/test/res/dumpModel.desc.xml, dynawo/sources/Models/CPP/Common/DYNModelCPPImpl.cpp, dynawo/sources/Models/CPP/Common/DYNModelCPPImpl.h, dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.h, dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.cpp, dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.h, dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/test/TestOmegaRef.cpp, dynawo/sources/Models/CPP/ModelFrequency/ModelSignalN/DYNModelSignalN.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.h, dynawo/sources/Models/CPP/ModelVariationArea/DYNModelVariationArea.h, examples/DynaWaltz/IEEE14/IEEE14_CascadingLineTrippings/IEEE14.par, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_UnderVoltageAutomaton/IEEE14.par
In this dev, a few open points/questions remain (that could be solved or modified later on if necessary):
- There is currently no proper method to deal with optional parameters at the submodel level (I had to use the getSubModelParameterValue method initially created for parameter curves) but a lot of the intelligence is duplicated in the submodel and networkComponentImpl classes to handle the non throw aspect. It is kind of a pity for me in terms of maintenance. In addition, there is certainly room for performances improvements in the networkComponentImpl ones (not to search for each parameter in the whole map, etc.)
- As of today, I throw with an error type "Modeler" which is quite common. If we want to catch this in dyn-itf to render a proper status, either we keep it this way and …
=> #1445 Add a protection against frequency collapse or increase

util/envDynawo.sh
When autocompletion is performed, set_commit_hook is called,
leading to issue if we are not in the main repo
=> #1574 Correct autocompletion

.github/workflows/ci.yml
It will not work for the moment as the new image is not built yet
=> #1775 Fix CI for v12x using new docker image dedicated for v12x.

dynawo/sources/Modeler/Common/DYNConnectorCalculatedVariable.cpp, dynawo/sources/Modeler/Common/DYNConnectorCalculatedVariable.h, dynawo/sources/Modeler/Common/DYNSubModel.cpp, dynawo/sources/Modeler/Common/DYNSubModel.h, dynawo/sources/Modeler/Common/test/Test.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManager.h, dynawo/sources/Modeler/ModelManager/DYNModelModelica.h, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/headerPatternDefine.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/modelWriter.py, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.h, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Init.h, dynawo/sources/Models/CPP/Common/DYNModelCPP.h, dynawo/sources/Models/CPP/Common/DYNModelCPPImpl.h, dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.h, dynawo/sources/Models/CPP/Controls/Shunts/ModelCentralizedShuntsSectionControl/DYNModelCentralizedShuntsSectionControl.h, dynawo/sources/Models/CPP/Events/ModelVariationArea/DYNModelVariationArea.h, dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/DYNModelVoltageSetPointChange.h, dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.h
A lot of checkDataCoherence functions are empty function, generating a lot of pointless calls. So we check a boolean to determine if the function is not empty
=> #1851 Improve performance for data check coherence

dynawo/CMakeLists.txt, dynawo/sources/Common/DYNCommon.cpp, dynawo/sources/Common/DYNCommon.h, dynawo/sources/Modeler/Common/DYNModelMulti.cpp, dynawo/sources/Modeler/DataInterface/DYNComponentInterface.hpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.cpp
Removing -Wno-float-conversion causes errors !
```
error: implicit conversion turns floating-point number into integer: 'double' to 'unsigned int' [-Werror,-Wfloat-conversion]
error: implicit conversion turns floating-point number into integer: 'double' to 'std::vector<int, std::allocator<int> >::value_type' (aka 'int') [-Werror,-Wfloat-conversion]
...
```
See #125
=> #125 fix clang compilation -Wfloat-conversion

dynawo/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCurrentLimitInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestCurrentLimitInterface.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
Removing -Wno-float-equal causes errors !
`error: comparing floating point with == or != is unsafe [-Werror,-Wfloat-equal]`
See #125
=> #125 fix clang compilation -Wfloat-equal

dynawo/CMakeLists.txt, dynawo/sources/API/CRT/CRTXmlHandler.cpp, dynawo/sources/API/CRT/test/TestXmlImporter.cpp, dynawo/sources/API/CRV/CRVXmlHandler.cpp, dynawo/sources/API/CRV/test/TestXmlImporter.cpp, dynawo/sources/API/DYD/DYDXmlHandler.cpp, dynawo/sources/API/DYD/test/Test.cpp, dynawo/sources/API/EXTVAR/EXTVARXmlHandler.cpp, dynawo/sources/API/EXTVAR/test/Test.cpp, dynawo/sources/API/FS/FSXmlHandler.cpp, dynawo/sources/API/FS/test/TestXmlImporter.cpp, dynawo/sources/API/JOB/JOBXmlHandler.cpp, dynawo/sources/API/JOB/test/TestXmlImporter.cpp, dynawo/sources/API/PAR/PARXmlHandler.cpp, dynawo/sources/API/PAR/test/TestXmlImporter.cpp, dynawo/sources/Common/gtest_dynawo.h, dynawo/sources/Modeler/Common/DYNSubModelFactory.cpp, dynawo/sources/Modeler/Common/DYNSubModelFactory.h, dynawo/sources/Modeler/Common/test/CompilerTest.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.hpp, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h, dynawo/sources/Solvers/AlgebraicSolvers/test/TestBasics.cpp, dynawo/sources/Solvers/Common/DYNSolverFactory.cpp, dynawo/sources/Solvers/Common/DYNSolverFactory.h, dynawo/sources/Solvers/SolverIDA/test/TestBasics.cpp, dynawo/sources/Solvers/SolverSIM/test/TestBasics.cpp
Removing -Wno-global-constructors causes errors !
```
error: declaration requires a global constructor [-Werror,-Wglobal-constructors]
error: declaration requires a global destructor [-Werror,-Wglobal-constructors]
```
See #125
=> #125 fix clang compilation -Wglobal-constructors

dynawo/CMakeLists.txt, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.cpp
Removing -Wno-missing-noreturn causes errors !
`error: function 'XXX' could be declared with attribute 'noreturn' [-Werror,-Wmissing-noreturn]`
See #125
=> #125 fix clang compilation -Wmissing-noreturn

dynawo/CMakeLists.txt, dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h, dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.cpp, dynawo/sources/Models/CPP/Events/ModelVariationArea/DYNModelVariationArea.cpp, dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/DYNModelVoltageSetPointChange.cpp, dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelSwitch.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/TestDerivatives.cpp
Removing -Wno-old-style-cast causes errors !
`error: use of old-style cast [-Werror,-Wold-style-cast]`
See #125
=> #125 fix clang compilation -Wold-style-cast

dynawo/CMakeLists.txt, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.h, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINSubModel.h
Removing -Wno-reserved-id-macro causes errors !
`error: macro name is a reserved identifier [-Werror,-Wreserved-id-macro]`
See #125
=> #125 fix clang compilation -Wreserved-id-macro

dynawo/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.h
Following flags must be kept (comments added in root CMakeLists.txt):
```
-Wno-exit-time-destructors
-Wno-padded
-Wno-sign-conversion
-Wno-used-but-marked-unused
-Wno-zero-as-null-pointer-constant
```
Following flags are useless and could be removed:
```
-Wno-conditional-uninitialized
-Wno-extra-semi
-Wno-mismatched-tags
-Wno-return-type
-Wno-sometimes-uninitialized
-Wno-overloaded-virtual
```
See #125
=> #125 fix clang compilation: remove useless flags, keep needed

dynawo/CMakeLists.txt, dynawo/sources/Modeler/Common/DYNCompiler.cpp, dynawo/sources/Modeler/Common/test/TestDelay.cpp
Removing `-Wno-unused-exception-parameter` causes an error !
`error: unused exception parameter 'e' [-Werror,-Wunused-exception-parameter]`
Removing `-Wno-unused-private-field` causes an error !
`error: private field 'rmModels_' is not used [-Werror,-Wunused-private-field]`
`-Wno-unused-macros` is useless and can be removed.
See #125
=> #125 fix clang compilation -Wunused-exception-parameter -Wunused-private-field

dynawo/sources/Simulation/DYNSimulation.cpp, dynawo/sources/Simulation/DYNSimulation.h
Recent commits cause errors:
`error: constructor parameter 'iidmFile' shadows the field 'iidmFile' of 'ExportStateDefinition' [-Werror,-Wshadow-field-in-constructor]`
See #125 and #1878
=> #125 fix clang compilation -Wshadow-field-in-constructor

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/SecondOrder.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/package.order, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/Limiter.mo
Creates a new SecondOrder block in order to allow a functioning simulation under Dynawo. Block may be deleted if the problem the MSL component is solved.
=> 2087 new SecondOrder

dynawo/sources/Models/CPP/ModelNetwork/test/TestBus.cpp
=> #1689 put back static to avoid missing-prototypes warning in clang

dynawo/sources/Common/DYNGraph.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNVoltageLevelInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.h
add a tie-breaker in connectNode to select the path with the lowest number of switches to activate
closes #2180
=> #2180 Fix exploration of graph to find all paths between two nodes, and

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVTfo.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVTfoDiagramPQ.mo
=> #2721 avoid adept to fail when GeneratorPVTfo is disconnected

dynawo/sources/Modeler/DataInterface/DYNCommonConstants.h, dynawo/sources/Modeler/DataInterface/DYNCriteria.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBusInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCalculatedBusInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestBusInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestDataInterface.cpp
missing in the iidm input file
closes #2781
=> #2781 use vnom instead of 1 (hard coded value) when a voltage value is

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestDataInterface.cpp
=> #3049 revert as current version does not modify the powers in case of

dynawo/sources/Modeler/Common/DYNModelMulti.cpp
=> #3068 Replacement of the underscore by a vertical bar in variables.log

dynawo/sources/API/LEQ/LEQLostEquipmentsCollection.cpp, dynawo/sources/API/LEQ/LEQLostEquipmentsCollection.h
=> #3153 LostEquipmentsCollection::lostEquipments_ vector is turned to a set

dynawo/sources/Solvers/VariableTimeStep/SolverIDA/DYNSolverIDA.cpp
=> #3263 initialize roots in IDA to ROOT_DOWN to avoid massive modification

dynawo/sources/Modeler/Common/DYNDynamicData.cpp, dynawo/sources/Modeler/Common/DYNDynamicData.h
=> #3284 Adapt DynamicData API.

dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp
outputs of the jobs. It should not be the case
closes #3417
=> #3417 the number of roots of the bus network model was dependent on the

dynawo/sources/Models/CPP/ModelNetwork/DYNModelCurrentLimits.cpp
=> #3398 [Constraints] when current overload happens, the value dumped is 0 instead of the value before opening

dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.h
them in the init model values
closes #3529
=> #3529 init values v17

dynawo/sources/Common/Dictionaries/validateDictionaries.py, dynawo/sources/Common/test/TestValidateDic.cpp
=> #3652 Add info when dictionnaries are not the same.
