dynawo/dynawo

README.md
=> #5 Updated README with documentation and site links.

dynawo/3rdParty/sundials/LICENSE
=> #14 Add Sundials license file

util/envDynawo.sh
Config for commentchar is now modified to be able to start comments with #.
Fix #9
=> #9 Config for commentchar

util/envDynawo.sh
=> #20 Fix set commit hook not thread safe because of git config command.

.gitignore, README.md, dynawo/3rdParty/xerces-c/xerces-c-chain.sh, util/envDynawo.sh
And some cleaning of shell scripts to harmonize them. 
Fix #17
=> #17 Added a Xerces-c toolchain compilation.

dynawo/3rdParty/adept/adept-chain-1.1.sh, dynawo/3rdParty/libiidm/libiidm-chain.sh, dynawo/3rdParty/libxml/CMakeLists.txt, dynawo/3rdParty/libxml/libxml-chain.sh, dynawo/3rdParty/libzip/libzip-chain.sh, dynawo/3rdParty/nicslu/nicslu-chain.sh, dynawo/3rdParty/omcUpdate_1_9_4/checkoutOpenModelica.sh, dynawo/3rdParty/omcUpdate_1_9_4/cleanBeforeLaunch.sh, dynawo/3rdParty/omcUpdate_1_9_4/omcUpdateDynawo.sh, dynawo/3rdParty/suitesparse/suitesparse-chain.sh, dynawo/3rdParty/sundials/sundials-chain-2-7-0.sh, dynawo/3rdParty/toolchain.sh, dynawo/CMakeLists.txt, dynawo/sources/Launcher/execDynawo.sh, util/envDynawo.sh
Some available options for compilation are now really useable as env variables are transmitted properly.
Fix #23.
=> #23 Some cleaning of shell scripts to harmonize them. 

util/envDynawo.sh
Corrected some mistakes in bash syntax.
=> #32 Changed build-doc in build-doc-doxygen. 

README.md
=> #34 Updated README with Docker information.

dynawo/sources/API/PAR/PARXmlExporter.cpp, dynawo/sources/Common/DYNCommun.cpp, dynawo/sources/Modeler/Common/DYNConnector.cpp, dynawo/sources/Modeler/Common/DYNSubModel.cpp, dynawo/sources/Modeler/DataInterface/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/DYNRatioTapChangerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/DYNStaticVarCompensatorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelSwitch.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelVoltageLevel.cpp, dynawo/sources/Solvers/Common/DYNSolverImpl.cpp, dynawo/sources/Solvers/SolverIDA/DYNSolverIDA.cpp, dynawo/sources/Solvers/SolverKINSOL/DYNSolverKIN.cpp, dynawo/sources/Solvers/SolverSIM/DYNSolverSIM.cpp
Fix of "Jump statements should not be followed by dead code" and "The original exception object should be rethrown"
=> #51 : Fix sonar issues

.gitignore, .travis.yml, README.md, documentation/dynawo_documentation.sh, documentation/installation/installation.tex, documentation/licenses/xerces-c/license.tex, util/envDynawo.sh
Added reference to compilation options in README.
=> #87 Forced some variables in envDynawo. 

dynawo/sources/Models/Modelica/Dynawo/Electrical/Constants.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/GoverProportional.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Transformers/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Transformers/BaseClasses_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Transformers/PhaseShifterI.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Transformers/PhaseShifterI_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Transformers/PhaseShifterP.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Transformers/PhaseShifterP_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Transformers/TapChanger.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Events/Event.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/GeneratorPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/GeneratorPV.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Transformers/BaseClasses_INIT.mo
The BaseClasses.mo file for the machine is completely modified because I applied a dos2unix command on it to delete windows end line characters
=> #25 Coding style for enumeration and constants

dynawo/cmake/FindLibArchive.cmake, dynawo/sources/API/DYD/DYDIdentifiableImpl.h, dynawo/sources/API/DYD/DYDMacroConnectorImpl.h, dynawo/sources/API/DYD/DYDMacroStaticReferenceImpl.h, dynawo/sources/API/DYD/DYDUnitDynamicModelImpl.h, dynawo/sources/API/EXTVAR/EXTVARVariableImpl.h, dynawo/sources/API/JOB/JOBAppenderEntryImpl.h, dynawo/sources/API/JOB/JOBConstraintsEntryImpl.h, dynawo/sources/API/JOB/JOBCurvesEntryImpl.h, dynawo/sources/API/JOB/JOBDynModelsEntryImpl.h, dynawo/sources/API/JOB/JOBFinalStateEntryImpl.h, dynawo/sources/API/JOB/JOBInitValuesEntryImpl.h, dynawo/sources/API/JOB/JOBInitialStateEntryImpl.h, dynawo/sources/API/JOB/JOBJobEntryImpl.h, dynawo/sources/API/JOB/JOBLogsEntryImpl.h, dynawo/sources/API/JOB/JOBModelerEntryImpl.h, dynawo/sources/API/JOB/JOBModelsDirEntryImpl.h, dynawo/sources/API/JOB/JOBNetworkEntryImpl.h, dynawo/sources/API/JOB/JOBOutputsEntryImpl.h, dynawo/sources/API/JOB/JOBSimulationEntryImpl.h, dynawo/sources/API/JOB/JOBSolverEntryImpl.h, dynawo/sources/API/JOB/JOBTimelineEntryImpl.h, dynawo/sources/Modeler/Common/DYNModelMulti.cpp, dynawo/sources/Modeler/DataInterface/DYNDataInterfaceIIDM.cpp, dynawo/sources/Simulation/CMakeLists.txt, dynawo/sources/Solvers/Common/DYNSolverImpl.cpp
In cxx11 added some std::move to comply with clang warnings.
=> #128 Added some virtual that were missing on destructors. 

dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousThreeWindings.xml
- GeneratorSynchronousThreeWindings.xml (with setpoint regulations)
=> #163 Three windings generator preassembled model

dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousFourWindingsProportionalRegulations.xml, dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousThreeWindingsProportionalRegulations.xml
- 3 windings and 4 windings generators with a proportional governor and a proportional voltage regulator.
- Associated non regression tests will be pushed with newer IEEE14 test cases
=> #168 Generators preassembled models with proportional regulations

dynawo/sources/Models/Modelica/Dynawo/Electrical/Transformers/BaseClasses_INIT.mo
Rewrite the function with additional comments and better notations.
=> #129 Modify the tapEstimation function

util/travis_ci/launch_command.sh
to avoid timeout because of sonar analysis.
=> #224 Avoid building 3rd parties on master push in Travis

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/VRProportional.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/VRProportionalIntegral.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/VRProportionalReactiveFeedback.extvar
- extvar files were deleted in #221, it was a mistake.
=> #239 Recreate extvar files for VR models

dynawo/sources/Modeler/DataInterface/test/TestStateVariable.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
- tolV was to be considered only in ratioTapChanger cases
=> #271 fix 2 windings trnasformer model and unit test

dynawo/sources/Modeler/DataInterface/test/TestIIDMModels.cpp, dynawo/sources/Modeler/DataInterface/test/TestStateVariable.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/Test.cpp, dynawo/sources/Solvers/SolverIDA/test/jobs/solverTestDelta.par, dynawo/sources/Solvers/SolverSIM/test/jobs/solverTestDelta.par, nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectGroup/IEEE14.par, nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLine/IEEE14.par, nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_LoadVariation/IEEE14.par, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/IEEE14.par, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/IEEE14.par, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroStaticRefs/IEEE14.par, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ModelicaModel/IEEE14.par, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/IEEE14.par, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_CurrentLimitAutomaton/IEEE14.par, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_PhaseShifterI/IEEE14.par, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_PhaseShifterP/IEEE14.par, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/IEEE14.par, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChangerCpp/IEEE14.par, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChangerLock/IEEE14.par, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_UnderVoltageAutomaton/IEEE14.par, nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/IEEE57.par, nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_2_DisconnectGroup/IEEE57.par, nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_3_DisconnectLine/IEEE57.par
DANGLING_LINE -> dangling_line
LINE -> line
TFO -> transformer
BUS -> bus
REACTANCE -> reactance
CAPACITOR -> capacitor
LOAD -> load
=> #267 network parameters in lower case

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/BaseClasses_INIT.mo
atan would return an angle between -Pi/2 and Pi/2 that might not be the true argument of the considered complex.
=> #613 Arg function instead of atan in machine model's theta initialization

documentation/functionalDoc/functionalDoc.tex, documentation/latex_setup.tex
Update the Modelica library part.
Update the solvers part.
=> #641 Update documentation

dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/Bus.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBus.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Lines/Line.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Switches/IdealSwitch.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Transformers/TransformerVariableTap.mo
It is a first step into the direction of being able to connect together elements from the library in OMEdit.
In addition to this development, the following questions remain open:
1. Replace ImPin connectors by RealInput or RealOutput.
2. Deal with some problems when the terminals are used in partial models while being declared in the final model (for example with some transformers). They don't get a graphical view with this development.
=> #651 Adding graphical view for the terminals

documentation/functionalDoc/functionalDoc.tex
- SVarC
- Converters
- preassembled models
=> #737 Documentation update

dynawo/sources/Models/Modelica/Dynawo/AdditionalIcons/package.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Examples/Overview.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/SMIBStepPm.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/SMIB_StepPm.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/package.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/package.order, dynawo/sources/Models/Modelica/Dynawo/Examples/package.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/package.order, dynawo/sources/Models/Modelica/Dynawo/package.order
First test case with graphical view and description. Ideas and comments are welcome @cossartque @RomainLosseauRTE
=> #731 Section Examples in Dynawo Modelica library with SMIB_StepPm

dynawo/sources/Modeler/DataInterface/DYNGeneratorInterface.h, dynawo/sources/Modeler/DataInterface/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/test/TestIIDMModels.cpp
Expose qMin parameter for the generators
=> #756 Expose qMin for the generators

dynawo/sources/Models/CPP/ModelNetwork/DYNModelPhaseTapChanger.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelPhaseTapChanger.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelRatioTapChanger.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelRatioTapChanger.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTapChanger.h
Added a 'const' somewhere, will you see it ? No more virtual methods since we do not use it.
=> 873 cleanup since no need of virtual functions

dynawo/sources/Models/Modelica/Dynawo/AdditionalIcons/package.mo, dynawo/sources/Models/Modelica/Dynawo/AdditionalIcons/package.order, dynawo/sources/Models/Modelica/Dynawo/Electrical/Shunt.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Shunts/ShuntB.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Shunts/package.order, dynawo/sources/Models/Modelica/Dynawo/Electrical/package.order
please check and review the new shunt model
=> 1071_added new shunt model within Dynawo.Electrical

.gitignore, dynawo/sources/Common/DYNTraceStream.cpp, dynawo/sources/Common/DYNTraceStream.h
We gain significant time when tested in PtFige NRT.
[reports_nrt.zip](https://github.com/dynawo/dynawo/files/5181893/reports_nrt.zip)
=> #1100 Filter messages before streaming them in internal buffer

util/nrt_diff/nrtDiff.py
Usage:
python nrt_diff/nrtDiff.py --firstDirectory=<NRT_PATH> --secondDirectory=<NRT_PATH>/reference/
=> #1119 Fix nrtDiff script used in standalone.

dynawo/sources/Models/Modelica/Dynawo/Connectors/ACPower.mo
=> #1134 Fix unit of terminal V and i

dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/InjectorIDQ.mo
This is a first fix but we have other numerical issues...
=> #1104 Fix variables that shouldn't be private (accessed on the outside)

util/curvesToHtml/csvToHtml/csvToHtml.py
- to be compliant with python3
=> #1152 FixCsvToHtml

dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSC.mo, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/HvdcVSCEmulation.xml
It seems to work fine when used in an existent test case
=> #1179 Add preassembled model HvdcVscEmulation

dynawo/3rdParty/libxml/sax/formatter/include/internals/FormatterImpl.h, dynawo/3rdParty/libxml/sax/formatter/include/xml/sax/formatter/Formatter.h, dynawo/3rdParty/libxml/sax/formatter/src/Formatter.cpp, dynawo/3rdParty/libxml/sax/formatter/src/FormatterImpl.cpp, dynawo/3rdParty/libxml/sax/formatter/tests/Formatter.test.cpp, dynawo/sources/API/DYD/DYDExporter.h, dynawo/sources/API/DYD/DYDXmlExporter.cpp, dynawo/sources/API/DYD/DYDXmlExporter.h, dynawo/sources/API/PAR/PARExporter.h, dynawo/sources/API/PAR/PARXmlExporter.cpp, dynawo/sources/API/PAR/PARXmlExporter.h
=> Correct encoding when exporting XML files

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py
=> #1235 Correct parsing of delays

dynawo/sources/Modeler/Common/DYNCompiler.cpp, dynawo/sources/Modeler/Common/DYNDynamicData.cpp, dynawo/sources/Modeler/Common/DYNDynamicData.h, dynawo/sources/Modeler/Common/DYNModelMulti.cpp, dynawo/sources/Modeler/Common/DYNModelMulti.h, dynawo/sources/Modeler/Common/DYNModeler.cpp
=> #902 Optimize code in dynamic data load init

dynawo/sources/Modeler/Common/DYNConnector.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNBusBarSectionInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNStepInterfaceIIDM.h, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h, dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.h, dynawo/sources/Simulation/DYNSimulationLauncher.h, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.h, dynawo/sources/Solvers/SolverIDA/DYNSolverIDA.h
Headers should be auto sufficient and therefore shall include all headers they required. This PR aims to correct the problems that will occur when formatting and automatic header sorting will be done in the code
=> #1260 Improve header include

.gitignore, .vscode/settings.json, dynawo/sources/Modeler/Common/DYNDelay.cpp, dynawo/sources/Modeler/Common/DYNDelay.h, dynawo/sources/Modeler/Common/DYNDelayManager.cpp, dynawo/sources/Modeler/Common/DYNDelayManager.h, dynawo/sources/Modeler/Common/test/TestDelay.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h, dynawo/sources/Modeler/ModelManager/test/Test.cpp, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/modelWriter.py, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.h, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Init.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Init.h, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_Dyn.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_DynNoAliasNoCalcVar.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_DynNoCalcVar.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_DynSilentZ.cpp
Also put in configuration vscode configuration for future developpers
=> Implement mode change when delay can be computed

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemoteDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemoteDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/GeneratorPQPropDiagramPQSignalN.xml, dynawo/sources/Models/Modelica/PreassembledModels/GeneratorPVRemoteDiagramPQSignalN.xml
Once this PR is merged, the associated MR in dynawo-rte should be merged as well.
=> #1270 Complete the library of generators with remote voltage control

dynawo/sources/Modeler/DataInterface/DYNStaticVarCompensatorInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNStaticVarCompensatorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNStaticVarCompensatorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/test/TestIIDMModelsStaticParameters.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.h, dynawo/sources/Models/CPP/ModelNetwork/test/TestStaticVarCompensator.cpp
- Read the active power in the iidm
- Implement constant b/g behavior (and constant mode)
@rosiereflo can you have a special look at the unit test TestStaticVarCompensator because I was not sure what to keep and what to remove (but the tests work)
=> #1242 s var c cpp

dynawo/sources/Launcher/main.cpp
We cannot guarantee that log system is initialized
when the exception is thrown
fixes #1284
=> #1284 Print on stderr in case of exception in main

dynawo/sources/API/PAR/PARParametersSet.h
extracted from code before modification
=> #902 Correct comments

dynawo/sources/Modeler/DataInterface/CMakeLists.txt
Closes #1301 
Signed-off-by: Guillaume Pernin <guillaume.pernin@rte-france.com>
=> #1301 add line in cmakeList

dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.cpp
closes #1322 
Signed-off-by: Guillaume Pernin <guillaume.pernin@rte-france.com>
=> #1322 GetBusName: changed function

dynawo/3rdParty/libxml/sax/parser/include/xml/sax/parser/ComposableDocumentHandler.h, dynawo/3rdParty/libxml/sax/parser/include/xml/sax/parser/ComposableElementHandler.h, dynawo/3rdParty/libxml/sax/parser/include/xml/sax/parser/DocumentHandler.h, dynawo/3rdParty/libxml/sax/parser/include/xml/sax/parser/ElementHandler.h, dynawo/3rdParty/libxml/sax/parser/src/DocumentHandler.cpp, dynawo/3rdParty/libxml/sax/parser/src/ElementHandler.cpp
=> #1328 Correct c++11 compilation with clang

dynawo/sources/API/PAR/PARXmlExporter.cpp, dynawo/sources/API/PAR/test/res/exportedFile.par
close #1337
Signed-off-by: Guillaume Pernin <guillaume.pernin@rte-france.com>
=> #1337 Write in the par the componentId

dynawo/sources/Common/DYNTrace.cpp, dynawo/sources/Common/DYNTrace.h
=> #1314 Implement multithreading for traces

dynawo/sources/Common/DYNTrace.cpp, dynawo/sources/Common/DYNTrace.h
Crash at destruction in static compilation
=> #1314 Correct traces in static compilation

dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINAlgRestoration.cpp
=> #1350 Remove invalid read in the algebraic restoration

dynawo/sources/Modeler/DataInterface/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/DYNDataInterface.h, dynawo/sources/Modeler/DataInterface/DYNServiceManagerInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNServiceManagerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNServiceManagerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestServiceManagerInterface.cpp
=> #1339 Add API for bus connected by switch

dynawo/sources/API/TL/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/CMakeLists.txt, dynawo/sources/Modeler/ModelManager/ModelicaExternalC/CMakeLists.txt, dynawo/sources/ModelicaCompiler/compileCppModelicaModelInDynamicLib.cmake.in, dynawo/sources/Models/CPP/Common/CMakeLists.txt, dynawo/sources/Solvers/Common/CMakeLists.txt
Correct windows compilation
closes #1360
=> #1360 Link boost system

dynawo/sources/Modeler/DataInterface/DYNServiceManagerInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNServiceManagerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNServiceManagerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestServiceManagerInterface.cpp
=> 1335 add get regulated bus api

dynawo/sources/Modeler/DataInterface/IIDM/DYNDanglingLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDanglingLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestDanglingLineInterface.cpp
=> #1373 check if R and X are zero for dangling lines

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemote.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemote.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemoteDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemoteDiagramPQ.mo
@PerninGuillaume fyi.
@marcochiaramello the associated MR in dynawo-rte will follow.
=> #1380 Fix the use of pu in the models of generators with remote voltage regulation

dynawo/sources/Modeler/DataInterface/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
This PR is a report on the v121 of some elements from the master
=> #1389 Add Hvdc elements necessary

.vscode/settings.json, dynawo/3rdParty/CMakeLists.txt, dynawo/3rdParty/adept/patch/MSVC/adept.patch, dynawo/3rdParty/adept/patch/common/adept.patch
=> #1249 Update Adept version

.vscode/settings.json, util/nrt_diff/iidmDiff.py, util/nrt_diff/nrtDiff.py
=> #1404 Put IIDM nrt diff in a specific file

dynawo/sources/Common/DYNTrace.cpp, dynawo/sources/Common/DYNTrace.h, dynawo/sources/Simulation/DYNSimulationLauncher.cpp
=> #1408 Print basic information even if log is disabled

dynawo/sources/Simulation/DYNSimulationLauncher.cpp
=> #1408 Correct logging in simulation launcher

dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic, dynawo/sources/Modeler/Common/DYNModelMulti.cpp, dynawo/sources/Modeler/Common/DYNSubModel.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
Log decreasing (mode and z in network).
Small modification in the evalMode method: as the method is no longer called recursively in evalZMode, no need to really compare to the previous status.
=> #1440 Decrease the log level for some features

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPV.mo
Once this PR is validated, the MR in dynawo-rte can be validated (update of nrt).
=> #1486 Put UPu calculation inside the if running loop for BaseGeneratorSimplified

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/GridForming/GridForming.mo
@adriguir fyi: you will be able to run Erwan's test cases without changing the OM lib
=> #1104 Fix SMIB and GridForming OM test cases with recent OM version

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQProp.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDangling.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDanglingDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQProp.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropDiagramPQ.mo
For HvdcPQProp HvdcPQPropDangling model:
- Fix the NQ convention
For other models using NQ signal:
- Give the convention
=> #1539 DynaFlow : fix NQ convention in HvdcPQProp model

dynawo/3rdParty/libiidm/libiidm.cmake, dynawo/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNFictTwoWTransformerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNThreeWTransformerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestDataInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestFictVoltageLevelInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestServiceManagerInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestShuntCompensatorInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestThreeWTransformerInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestVoltageLevelInterface.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/TestIIDMInitializationFlow.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/TestShuntCompensator.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/TestThreeWindingsTransformer.cpp, util/envDynawo.sh
With support for node/breaker topologies including internal connections.
=> #1532 Upgrade to 1.3.2 version of powsybl-iidm4cpp

dynawo/sources/Modeler/DataInterface/IIDM/DYNShuntCompensatorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNShuntCompensatorInterfaceIIDM.h
=> #1561 adapting shunt data interface for iidm 1.0

dynawo/sources/Modeler/DataInterface/IIDM/DYNShuntCompensatorInterfaceIIDM.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp
=> #1561 fix documentation and shunt model

util/envDynawo.sh
=> #1574 Correct git config ins scripts

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.h
=> #1589 fix shunt doc for older doxygen versions

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses.mo
parameters moved from protected to public
=> #1600 BaseGeneratorSynchronous 

dynawo/sources/Models/CPP/ModelNetwork/test/TestLoad.cpp
=> #1594 Correct unit tests

dynawo/sources/Models/CPP/Controls/Shunts/ModelCentralizedShuntsSectionControl/DYNModelCentralizedShuntsSectionControl.h
=> #1613 fix shunt centralized model for cpp 98

dynawo/sources/Modeler/DataInterface/IIDM/DYNDanglingLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/test/TestStateVariable.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestSwitchInterface.cpp
=> #1638 discard switch with same extremities

dynawo/sources/Common/Dictionaries/validateDictionaries.py, dynawo/sources/Common/test/TestValidateDic.cpp, dynawo/sources/Common/test/dic/allInOne/AIOMyDic_fr_FR.dic, dynawo/sources/Common/test/dic/allInOne/AIOMyLog_en_GB.dic, dynawo/sources/Common/test/dic/allInOne/AIOMyLog_fr_FR.dic, dynawo/sources/Common/test/dic/allInOne/AIOMyLog_keys_ref.cpp, dynawo/sources/Common/test/dic/allInOne/AIOMyLog_keys_ref.h, dynawo/sources/Common/test/dic/allInOne/AIOMyTimelinePriority.dic, dynawo/sources/Common/test/dic/allInOne/AIOMyTimeline_en_GB.dic, dynawo/sources/Common/test/dic/allInOne/AIOMyTimeline_fr_FR.dic, dynawo/sources/Common/test/dic/allInOne/AIOMyTimeline_keys_ref.cpp, dynawo/sources/Common/test/dic/allInOne/AIOMyTimeline_keys_ref.h, dynawo/sources/Common/test/dic/allInOne/otherDir/include/AIOMyDic_keys.h, dynawo/sources/Common/test/dic/allInOne/otherDir/share/AIOMyDic_en_GB.dic, dynawo/sources/Common/test/dic/argsCount/ArgsCount_en_GB.dic, dynawo/sources/Common/test/dic/argsCount/ArgsCount_fr_FR.dic, dynawo/sources/Common/test/dic/capitalInLog/CapitalInLog.dic, dynawo/sources/Common/test/dic/differentKeys/DifferentKeys_en_GB.dic, dynawo/sources/Common/test/dic/differentKeys/DifferentKeys_fr_FR.dic, dynawo/sources/Common/test/dic/noSeparator/NoSeparator.dic, dynawo/sources/Common/test/dic/noTimeline/MyTimelinePriority.dic, dynawo/sources/Common/test/dic/timelinePriorityLocale/MyTimelinePriority_en_GB.dic
=> #1646 unify validateDictionaries

dynawo/sources/Common/Dictionaries/validateDictionaries.py, dynawo/sources/Common/test/TestValidateDic.cpp, util/nrt_diff/test/nrtDiffTest.py
=> #1665 fix python 3 issues

dynawo/sources/Common/DYNIoDico.cpp
=> #1679 default locale when adding dictionary

dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/TestBus.cpp
=> #1676 resolve ACPIN inconsistency in bus model and remove PWPIN

dynawo/sources/Common/Dictionaries/DYNError_en_GB.dic, dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.h, dynawo/sources/Models/CPP/ModelNetwork/test/TestBus.cpp
=> #1690 fix bus state change for node-breaker

dynawo/3rdParty/boost/patch/MSVC/boost.patch
=> #1723 Update boost patch for 1.70 on MSVC.

dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.cpp
=> #1731 Fix dangling line state change

dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.cpp, dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.h, dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/test/TestLoadRestorativeWithLimits.cpp
=> #1707 fix alpha beta load disconnection and add log to timeline

dynawo/sources/Modeler/DataInterface/DYNPhaseTapChangerInterface.h, dynawo/sources/Modeler/DataInterface/DYNRatioTapChangerInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNPhaseTapChangerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNPhaseTapChangerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNRatioTapChangerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNRatioTapChangerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/test/TestStateVariable.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNPhaseTapChangerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNPhaseTapChangerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNRatioTapChangerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNRatioTapChangerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestPhaseTapChangerInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestRatioTapChangerInterface.cpp
=> #1728 expose targetDeadBand values for Ratio and Phase Tap Changers

dynawo/sources/Modeler/DataInterface/DYNGeneratorInterface.h, dynawo/sources/Modeler/DataInterface/DYNStaticVarCompensatorInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNStaticVarCompensatorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNStaticVarCompensatorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/test/TestStateVariable.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNStaticVarCompensatorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNStaticVarCompensatorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestGeneratorInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestStaticVarCompensatorInterface.cpp
=> #1727 add required iidm public extensions

dynawo/sources/Modeler/DataInterface/IIDM/test/TestDataInterfaceIIDM.cpp
=> #1735 Correct centos6 and centos7 compilation

util/nrt_diff/nrtDiff.py, util/nrt_diff/test/nrtDiffTest.py
=> #1748 Fix dyn algorithm nrt and python unit tests

dynawo/sources/API/CRT/test/TestXmlImporter.cpp, dynawo/sources/API/CRV/test/TestXmlImporter.cpp, dynawo/sources/API/DYD/test/Test.cpp, dynawo/sources/API/EXTVAR/test/Test.cpp, dynawo/sources/API/FS/test/TestXmlImporter.cpp, dynawo/sources/API/JOB/test/TestXmlImporter.cpp, dynawo/sources/API/PAR/test/TestXmlImporter.cpp, dynawo/sources/Modeler/Common/test/CompilerTest.cpp, dynawo/sources/Solvers/AlgebraicSolvers/test/TestBasics.cpp, dynawo/sources/Solvers/SolverIDA/test/TestBasics.cpp, dynawo/sources/Solvers/SolverSIM/test/TestBasics.cpp, dynawo/sources/Test/initXml.cpp
=> #1615 Fix XML initialization for some unit tests

dynawo/sources/API/CRT/CRTCriteria.cpp, dynawo/sources/API/CRT/CRTCriteria.h, dynawo/sources/API/CRT/CRTXmlHandler.cpp, dynawo/sources/API/CRT/CRTXmlHandler.h, dynawo/sources/API/CRT/test/TestCriteria.cpp, dynawo/sources/API/CRT/test/TestXmlImporter.cpp, dynawo/sources/API/CRT/test/res/criteria.crt, dynawo/sources/API/CRT/xsd/criteria.xsd, dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic, dynawo/sources/Modeler/DataInterface/IIDM/DYNCalculatedBusInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNCalculatedBusInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/test/TestCriteria.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCalculatedBusInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCalculatedBusInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestCriteria.cpp, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.h
=> #1744 add voltage level criteria on node breaker nodes

dynawo/sources/API/CRT/CRTCriteria.cpp, dynawo/sources/API/CRT/CRTCriteria.h, dynawo/sources/API/CRT/CRTCriteriaImpl.cpp, dynawo/sources/API/CRT/CRTCriteriaImpl.h, dynawo/sources/API/CRT/CRTXmlHandler.cpp, dynawo/sources/API/CRT/CRTXmlHandler.h, dynawo/sources/API/CRT/test/TestCriteria.cpp, dynawo/sources/API/CRT/test/TestXmlImporter.cpp, dynawo/sources/API/CRT/test/res/criteria.crt, dynawo/sources/API/CRT/xsd/criteria.xsd, dynawo/sources/API/DYD/DYDDynamicModelsCollectionImpl.h, dynawo/sources/API/EXTVAR/EXTVARVariablesCollectionImpl.h, dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic, dynawo/sources/Modeler/DataInterface/IIDM/DYNCalculatedBusInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNCalculatedBusInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/test/TestCriteria.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCalculatedBusInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCalculatedBusInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestCriteria.cpp, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.h
=> #1744 add voltage level criteria on node breaker nodes v1.2.2

util/timeline_filter/timelineFilter.py
=> #1639 Fix timeline filter so that it runs on centos6

dynawo/sources/Modeler/DataInterface/DYNDataInterfaceFactory.cpp
=> #1735 Correct flag for powsybl use

util/timeline_filter/timelineFilter.py
=> #1639 Fix timeline filter for centos6 (part 2)

dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/DYNModelVoltageSetPointChange.cpp, dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/DYNModelVoltageSetPointChange.h
=> #1717 Fix doxygen.

dynawo/sources/Modeler/DataInterface/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/DYNCurrentLimits.h, dynawo/sources/Modeler/DataInterface/DYNGeneratorInterface.h, dynawo/sources/Modeler/DataInterface/DYNHvdcLineInterface.h, dynawo/sources/Modeler/DataInterface/DYNLineInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNHvdcLineInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNLineInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCurrentLimitsPerSeasonIIDMExtension.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorActivePowerControlIIDMExtension.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcAngleDroopActivePowerControlIIDMExtension.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcOperatorActivePowerRangeIIDMExtension.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.hpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensionsTraits.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensionsTraits.hpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLineInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestGeneratorInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestHvdcLineInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestLineInterface.cpp
Added IIDM extensions:
- current limit per season IIDM
- generator active power control IIDM
- HVDC power active control IIDM
- HVDC active power range IIDM
=> #1749 Add rest of IIDM extensions

nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__10_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__11_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__12_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__13_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__14_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___2_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___3_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___4_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___5_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___6_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___9_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__10_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__11_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__12_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__13_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD__14_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___2_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___3_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___4_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___5_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___6_EC.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___9_EC.txt, util/nrt_diff/nrtDiff.py, util/nrt_diff/test/nrtDiffTest.py
=> #1805 Fix comparison of discrete variables initial values

dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.hpp
=> #1820 Add log to notify when IIDM extension library is not found

dynawo/sources/Modeler/DataInterface/test/TestDataInterface.cpp
=> #1828 fix test datainterface on Centos

dynawo/sources/API/JOB/JOBSimulationEntry.cpp, dynawo/sources/API/JOB/JOBSimulationEntry.h, dynawo/sources/API/JOB/test/TestSimulationEntry.cpp
=> #1832 set criteria file for JOB

dynawo/sources/API/JOB/JOBTimelineEntry.cpp, dynawo/sources/API/JOB/JOBTimelineEntry.h, dynawo/sources/API/JOB/JOBXmlHandler.cpp, dynawo/sources/API/JOB/test/TestTimelineEntry.cpp, dynawo/sources/API/JOB/test/TestXmlImporter.cpp, dynawo/sources/API/JOB/test/res/jobsExample.jobs, dynawo/sources/API/JOB/xsd/jobs.xsd, dynawo/sources/API/TL/TLCsvExporter.cpp, dynawo/sources/API/TL/TLCsvExporter.h, dynawo/sources/API/TL/TLExporter.h, dynawo/sources/API/TL/TLTxtExporter.cpp, dynawo/sources/API/TL/TLTxtExporter.h, dynawo/sources/API/TL/TLXmlExporter.cpp, dynawo/sources/API/TL/TLXmlExporter.h, dynawo/sources/API/TL/test/TestExporter.cpp, dynawo/sources/API/TL/test/res/testCsvTimelineExportWithoutTime.csv, dynawo/sources/API/TL/test/res/testTxtTimelineExportWithoutTime.txt, dynawo/sources/API/TL/test/res/testXmlTimelineExportWithoutTime.xml, dynawo/sources/API/TL/xsd/timeline.xsd, dynawo/sources/Simulation/DYNSimulation.cpp, dynawo/sources/Simulation/DYNSimulation.h
=> #1647 optional timing in timeline

dynawo/sources/Modeler/DataInterface/IIDM/DYNVscConverterInterfaceIIDM.cpp
=> #1818 Fix cp98 implementation

dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNBusInterfaceIIDM.cpp
=> #1794 Fix battery implementation

dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.h
=> #1794 Fix doxygen comments

util/nrt_diff/nrtDiff.py
=> #1886 improve Dynamic Time Warping distance eval for nrt

util/nrt_diff/iidmDiff.py, util/nrt_diff/nrtDiff.py
=> #1894 speed up iidm parsing using lxml

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.cpp
=> #1900 Fix regulated terminal

dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic, dynawo/sources/Models/CPP/Events/ModelVariationArea/DYNModelVariationArea.cpp
=> #1872 add timeline log when variation area starts and ends

dynawo/sources/Common/DYNCompatibility.h, dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponentImpl.hpp, util/warnings_to_filter.txt
=> #1960 fix doxygen warnings

util/warnings_to_filter.txt
=> #1960 Fix doxygen warning on centos7

dynawo/sources/API/JOB/JOBFinalStateEntry.h, dynawo/sources/API/JOB/JOBFinalStateEntryImpl.cpp, dynawo/sources/API/JOB/JOBFinalStateEntryImpl.h, dynawo/sources/API/JOB/JOBTimelineEntry.h, dynawo/sources/API/JOB/JOBTimelineEntryImpl.cpp, dynawo/sources/API/JOB/JOBTimelineEntryImpl.h, dynawo/sources/API/JOB/test/TestFinalStateEntry.cpp, dynawo/sources/API/JOB/test/TestTimelineEntry.cpp, dynawo/sources/API/JOB/test/TestXmlImporter.cpp, dynawo/sources/API/TL/TLCsvExporter.cpp, dynawo/sources/API/TL/TLExporter.h, dynawo/sources/API/TL/TLTxtExporter.cpp, dynawo/sources/API/TL/TLXmlExporter.cpp, dynawo/sources/API/TL/test/TestExporter.cpp, dynawo/sources/Simulation/DYNSimulation.cpp, dynawo/sources/Simulation/DYNSimulation.h
=> #1985 Stop using boost::optional in API JOB

dynawo/sources/Modeler/ModelManager/CMakeLists.txt, dynawo/sources/Models/CPP/ModelNetwork/CMakeLists.txt, dynawo/sources/Solvers/AlgebraicSolvers/CMakeLists.txt, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINAlgRestoration.cpp, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINAlgRestoration.h, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.cpp, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.h, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINEuler.cpp, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINEuler.h, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINSubModel.cpp, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINSubModel.h, dynawo/sources/Solvers/SolverSIM/DYNSolverSIM.h
=> #1951 dissociate solvers and KINSubModel

dynawo/CMakeLists.txt, dynawo/cmake/getgitheadrevision.cmake, dynawo/sources/CMakeLists.txt, dynawo/sources/Common/CMakeLists.txt, dynawo/sources/Launcher/CMakeLists.txt, dynawo/sources/Simulation/CMakeLists.txt
=> #1962 generate config.h and gitversion.h in build directory

util/nrt_diff/nrtDiff.py
=> #1998 fix nrt diff for input files other than dynawo jobs files

dynawo/sources/Solvers/AlgebraicSolvers/CMakeLists.txt
=> #1951 fix dynawo_SolverKINSOL link on Windows

util/xsl/README.md, util/xsl/applyXsltToXml.py
=> #945 enhance apply xsl script

dynawo/sources/Common/DYNTrace.cpp, dynawo/sources/Common/DYNTrace.h, dynawo/sources/Common/DYNTraceStream.cpp, dynawo/sources/Simulation/DYNSimulation.cpp, util/warnings_to_filter.txt
=> #2012 Fix logging for upper projects

dynawo/sources/Common/DYNIoDico.h, dynawo/sources/Modeler/Common/DYNConnector.cpp, dynawo/sources/Modeler/Common/DYNConnector.h, dynawo/sources/Modeler/Common/DYNDynamicData.h
=> #2007 Remove useless copy constructors

examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/base/finalState/500_outputIIDM.xml, examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/base/finalState/700_outputIIDM.xml, examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/base/finalState/outputIIDM.xml, examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/restart/finalState/700_outputIIDM.xml, examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/restart/finalState/outputIIDM.xml
IIDM schema version is incompatible with cpp98 compilation
=> #1934 Fix nrt

.github/workflows/nightly-release.yml
=> #1952 Remove "distributions." from asset names

dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.cpp, dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.h, dynawo/sources/Solvers/FixedTimeStep/SolverSIM/DYNSolverSIM.cpp, dynawo/sources/Solvers/FixedTimeStep/SolverTRAP/DYNSolverTRAP.cpp
=> #1974 Fix solver implementation

dynawo/sources/API/CSTR/CSTRConstraint.cpp, dynawo/sources/API/CSTR/CSTRConstraint.h, dynawo/sources/API/CSTR/CSTRConstraintsCollection.cpp, dynawo/sources/API/CSTR/CSTRConstraintsCollection.h, dynawo/sources/API/CSTR/CSTRXmlExporter.cpp, dynawo/sources/API/CSTR/test/CMakeLists.txt, dynawo/sources/API/CSTR/test/Test.cpp, dynawo/sources/API/CSTR/test/TestConstraint.cpp, dynawo/sources/API/CSTR/test/TestConstraintsCollection.cpp, dynawo/sources/API/CSTR/test/TestExporter.cpp, dynawo/sources/API/CSTR/xsd/constraints.xsd, dynawo/sources/Common/DYNMacrosMessage.h, dynawo/sources/Common/Dictionaries/DYNConstraint_en_GB.dic, dynawo/sources/Modeler/Common/DYNSubModel.cpp, dynawo/sources/Modeler/Common/DYNSubModel.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelCurrentLimits.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelCurrentLimits.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/TestCurrentLimits.cpp
=> #1822 Add detailed data to constraints

util/envDynawo.sh
=> #2060 Add dynawoEnv.txt to distribution with headers

dynawo/sources/Simulation/DYNSimulation.cpp
=> #1823 fix cpp03 compilation

dynawo/sources/API/FSV/FSVXmlHandler.cpp, dynawo/sources/API/FSV/FSVXmlHandler.h
=> #1823 fix clang build

dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/dataContainer.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py
closes #2102
closes #2109
- Make sure index of created relations is coherent between evalMode and evalF
- properly handle variable initialization
- call customParametersConstructors on init models
=> #2102 #2109 Fixes compilation scripts and model manager

util/curvesToHtml/csvToHtml/csvToHtml.py
=> #2135 do not generate names containing a # in javascript

dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManager.h, dynawo/sources/Modeler/ModelManager/DYNModelModelica.h, dynawo/sources/Modeler/ModelManager/test/Test.cpp, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/headerPatternDefine.py, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.h, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Init.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Init.h, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_Dyn.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_DynNoAliasNoCalcVar.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_DynNoCalcVar.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_DynSilentZ.cpp
=> #2049 modification submodel parameter

dynawo/sources/Common/DYNGraph.cpp, dynawo/sources/Common/DYNGraph.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestVoltageLevelInterface.cpp
=> #2033 Fix topological graph in case powsybl is used

util/nrt_diff/nrtDiff.py
=> #2104 fix missing package names in nrtDiff

dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp
=> #2161 do not generate static tpes of variable in init model

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQProp.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDangling.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDangling.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDanglingDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDanglingDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhi.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhi.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDangling.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDangling.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDanglingDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDanglingDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPV.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDangling.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDangling.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDanglingDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDanglingDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDiagramPQ.extvar, nrt/data/DynaFlow/HvdcPQPropDiagramPQ/HvdcPQPropDiagramPQ.dyd, nrt/data/DynaFlow/HvdcPowerTransfer/HvdcPowerTransfer.dyd
Associated MR are coming in dynawo-rte, dynawo-interface and dynaflow-launcher. They must all be merged together.
=> #2191 Have one switchOffSignal/running for each side of an HVDC

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestServiceManagerInterface.cpp
=> #2209 fix service manager when a battery is present

util/nrt_diff/defineTestReference.py
=> #2212 fix XMLUtils import

dynawo/sources/Common/DYNGraph.cpp, dynawo/sources/Common/DYNGraph.h, dynawo/sources/Common/test/TestGraph.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelVoltageLevel.cpp
=> #2206 remove findAllPaths and replace with Disjktra algorithms

dynawo/sources/Modeler/DataInterface/IIDM/DYNVoltageLevelInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp
(no breaker switch or internal connections)
=> #2206 Fix disconnectNode when there is no possibility to open a path

dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelGenerator.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.cpp
getIndexesOfVariablesUsedForCalculatedVarI to be resilient to running
state changes
closes #2130
=> #2130 Add all possibles dependencies in

dynawo/sources/Modeler/DataInterface/DYNLoadInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNLoadInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNLoadInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/test/TestIIDMModelsStaticParameters.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLoadInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLoadInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestLoadInterface.cpp
=> #2231 expose if load is fictitious

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/ExcIEEEST4B.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/ExcIEEEST4B_INIT.mo
The nrt have been successfully run.
=> #2242 Kludge removed, typing mistake corrected

.github/pull_request_template.md
=> #2282 add forgotten checks

dynawo/3rdParty/libiidm/libiidm.cmake
=> #1528 Fix compilation for windows.

dynawo/3rdParty/CMakeLists.txt, util/windows/deploy.cmd
=> #1528 Fix 2 compilation for windows.

util/envDynawo.sh
=> #2295 force the deploy of libboost_data_time.so

dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.h, dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnTypes.h, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py
=> #2263 support of Modelica.Blocks.MathBoolean.Or MSL block

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/BaseClasses_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses_INIT.mo
=> #2286 Non-zero start value for i0Pu (for branch 460_add_mteret)

dynawo/sources/Common/DYNTrace.cpp, dynawo/sources/Common/DYNTrace.h, util/warnings_to_filter.txt
=> #2280 add a method to reset a specific persistant appender

dynawo/sources/Common/DYNTrace.cpp, dynawo/sources/Common/DYNTrace.h, util/warnings_to_filter.txt
=> #2280 reset appender v13

README.md, documentation/README.md
=> #2314 update links to release following v1.3.0 creation

.github/workflows/release.yml
=> #2051 Fix workflow by calling targets to create new distribs.

.github/workflows/release.yml
=> #2336 Add centos7 distribution generation.

dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulationSet_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/HvdcPQPropDiagramPQEmulationSet.xml, dynawo/sources/Models/Modelica/PreassembledModels/HvdcPQPropEmulationSet.xml, dynawo/sources/Models/Modelica/PreassembledModels/HvdcPVDiagramPQEmulationSet.xml, dynawo/sources/Models/Modelica/PreassembledModels/HvdcPVEmulationSet.xml
=> #2345 AC Emulation without p0 recalculation

util/windows/deploy.cmd
=> #2348 Add a dynawo folder in windows zip.

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py
=> #2317 fix corner case when a calculated variable is a table named x

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/AbsLimRateLimFeedthroughFreeze.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/AbsLimRateLimFirstOrderFreeze.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/AbsLimRateLimFirstOrderFreezeLimDetection.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/AntiWindupIntegrator.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/DecreaseDetection.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/IncreaseDetection.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/IntegratorWithReset.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/package.order, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/DelayFlag.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/MultiSwitch.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/SwitchInteger.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/VariableDelayFlag.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/package.order
=> #2307 Implement NonElectrical blocks WT IEC

dynawo/sources/Modeler/Common/DYNModelMulti.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp, dynawo/sources/Models/CPP/Common/DYNModelCPP.cpp, dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.cpp
=> #2339 dump roots to avoid recomputing them at load

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNStaticVarCompensatorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestStaticVarCompensatorInterface.cpp, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/dataContainer.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py
within mixed equations
closes #2245
=> #2245 Better handle of mixed equation and added support for relatins

dynawo/sources/Common/DYNParameter.h
=> #2371 Fix doxygen.

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp
=> #2360 Fix windows load of iidm extensions.

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp
=> 2360 iidm extensions windows v13

.github/workflows/ci.yml
=> #2376 Update CI workflow to publish doxygen online.

README.md, dynawo/3rdParty/CMakeLists.txt, dynawo/CMakeLists.txt, dynawo/sources/Common/DYNCommon.h, dynawo/sources/Modeler/Common/DYNSubModelFactory.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.hpp, dynawo/sources/Solvers/Common/DYNSolverFactory.cpp
=> #2373 Fix compilation for Ubuntu 22.04 and Fedora 36.

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py
=> #2245 fix detection of useless tmp vars

dynawo/sources/API/EXTVAR/EXTVARVariable.cpp, dynawo/sources/API/EXTVAR/test/Test.cpp, dynawo/sources/Common/Dictionaries/DYNError_en_GB.dic, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/scriptVarExt.py
=> #2356 Allow optional external continuous variables

dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.cpp, nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLine/reference/outputs/lostEquipments/lostEquipments.xml, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_CurrentLimitAutomaton/reference/outputs/lostEquipments/lostEquipments.xml
=> 2355 fix legacy iidm unittests nrt v13

dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.cpp
=> #2355 Fix legacy iidm unittests lost equipments.

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/DoubleStep.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/DoubleStep.xml
=> #2388 double step v13

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/IntegratorVariableLimits.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/package.order
=> 2325 add integrator variable limits

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py
=> #2329 consider dummy der variables as differential

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/initValues/globalInit/dumpInitValues-LOADVAR_LOAD3.txt, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/initValues/globalInit/dumpInitValues-LOADVAR_LOAD3_P.txt, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/initValues/globalInit/dumpInitValues-LOADVAR_LOAD3_Q.txt, nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-LoadVariation.txt, nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-LoadVariation_P.txt, nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-LoadVariation_Q.txt
=> #2377 Handle Modelica.Blocks.Sources.CombiTimeTable

nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.par
=> #2343 Fix nrt by adding back useless network par set.

dynawo/sources/Modeler/Common/DYNParameterModeler.h, dynawo/sources/Solvers/Common/DYNParameterSolver.h
=> #117 Fix clang 10 compilation.

.github/workflows/nightly.yml
=> #2025 Remove matrix on cxx98 in nightly.

dynawo/sources/Models/CMakeLists.txt
=> #289 Fix windows compilation.

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/BooleanTable.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/CombiTimeTable.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/package.order, dynawo/sources/Models/Modelica/Dynawo/Electrical/Shunts/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Shunts/ShuntB.extvar, dynawo/sources/Models/Modelica/PreassembledModels/BooleanTable.xml, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/CombiTimeTable.xml, dynawo/sources/Models/Modelica/PreassembledModels/ShuntB.xml
=> #2363 CombiTimeTable and BooleanTable for Dynawo

dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQProp_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhi_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPV_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSC_INIT.mo, examples/DynaFlow/IllustrativeExamples/HVDC_CLA/HVDC_CLA.par, examples/DynaFlow/IllustrativeExamples/HVDC_PhaseShifter/HVDC_PhaseShifter.par, nrt/data/DynaFlow/HvdcDangling/HvdcDangling.par, nrt/data/DynaFlow/HvdcPQPropDiagramPQ/HvdcPQPropDiagramPQ.par, nrt/data/DynaFlow/HvdcPowerTransfer/HvdcPowerTransfer.par, nrt/data/HVDC/HVDC.par
=> #2374 hvdc: activePowerSetPoint is now a parameter

dynawo/sources/Models/Modelica/Dynawo/Connectors/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Connectors/IntPin.mo, dynawo/sources/Models/Modelica/Dynawo/Connectors/package.order, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/IntegerDoubleStep.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/IntegerDoubleStep.xml
=> #2425 IntegerDoubleStep added

dynawo/sources/Solvers/CMakeLists.txt
=> #2289 Fix windows build.

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDanglingLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNFictTwoWTransformerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLoadInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNStaticVarCompensatorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNTwoWTransformerInterfaceIIDM.cpp
=> #2439 terminals connection is not updated when in node breaker

dynawo/sources/API/JOB/JOBXmlHandler.cpp, dynawo/sources/API/JOB/xsd/jobs.xsd, dynawo/sources/Simulation/DYNSimulation.cpp, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.jobs, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.par
=> #2399 revert

dynawo/sources/API/JOB/JOBXmlHandler.cpp, dynawo/sources/API/JOB/xsd/jobs.xsd, dynawo/sources/Simulation/DYNSimulation.cpp, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.jobs, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.par
=> #2399 make par file and par id optional in network entry of jobs 2

dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/ActivePowerControl/BaseActivePowerControl.mo
=> #2463 Improve HvdcVSCEmulation init

dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/ActivePowerControl/BaseActivePowerControl.mo
=> #2463 Improve HvdcVSCEmulation init v1.3

dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/TestTwoWindingsTransformer.cpp
=> #2467 td params v13

dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp, dynawo/sources/Models/CPP/ModelNetwork/test/TestTwoWindingsTransformer.cpp
=> #2467 td params

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLoadInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestLoadInterface.cpp
=> #2476 fix isFictitious load interface method

dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.cpp
=> #2366 fix sonar centos7

dynawo/sources/Models/CPP/Events/ModelAreaShedding/DYNModelAreaShedding.h, dynawo/sources/Models/Modelica/Dynawo/Examples/ENTSOE/TestCase2.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/ENTSOE/TestCase3.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/GridForming/GridForming.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/Standard/GovSteam1ExcIEEEST4BPssIEEE2B2.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/Standard/GovSteam1ExcIEEEST4BPssIEEE2B3.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCFaultImp.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCLoadVarQ.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCLoadVarQLarge.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCModeChange.mo
=> #2342 fix Modelica examples

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation.mo
=> #2480 Add a parameter Enabled0 in AC Emulation v1.3

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation.mo
=> #2480 Add a parameter Enabled0 in AC Emulation v1.3.0.1

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation.mo
=> #2480 Add a parameter Enabled0 in AC Emulation

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPV.mo
corresponding MR in dynawoRTE and dynawoInterface
=> #2424 T param default value removed

util/nrt_diff/nrtDiff.py
=> #2487 DTW matrix was not properly initialized

util/nrt_diff/test/nrtDiffTest.py
=> #2487 fix python unit tests

dynawo/sources/Models/CMakeLists.txt
=> #2502 Fix No rule to make target M/M/D/N/L/ConstraintKeys.mo

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPV.mo, nrt/nrt.py
=> #2423 run only failed nrt

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py
=> #2428 fix adept v13

dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/LoadAlphaBetaMotor.xml
=> #10 Add LoadAlphaBetaMotor model

util/xsl/2424.par.xsl
=> #2424 add xsl for T param in GeneratorPV

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py
=> #2506 fix detection of variables

util/nrt_diff/nrtDiff.py
=> #2513 different color for paths in nrt html report

util/curvesToHtml/csvToHtml/csvToHtml.py, util/curvesToHtml/resources/curves_ref.js.in
curves-reference-same-graph
closes #2514
=> #2514 plot at the same time the result and the reference graph in

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/Switch.extvar, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/Switch.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/Switch.xml
=> #2301 switch shunt

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulationSet_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulationVariableK.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulationVariableK_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/Parameters.mo, nrt/data/DynaFlow/HvdcPowerTransfer/HvdcPowerTransfer.par
=> #2494 AC Emulation : use the proper p0 and start value for delta theta filtered

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/DoubleStep.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/IntegerDoubleStep.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/Perturbation.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SetPoint_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SineWave.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/SineWave.xml
=> #2541 SineWave model added, descriptions corrected

dynawo/3rdParty/suitesparse/patch/MSVC/suitesparse.patch
=> #2239 fix windows compil v13

README.md, documentation/README.md, documentation/introduction/introduction.tex
=> #2564 update links in documentation following release 1.3.1

dynawo/sources/Modeler/DataInterface/DYNCriteria.h, util/warnings_to_filter.txt
=> #2246 Doxygen build fix

util/windows/dynawo.cmd
=> #2578 Fix dynawo.cmd

util/windows/dynawo.cmd
=> 2578 fix dynawo cmd v13

dynawo/sources/Modeler/DataInterface/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/DYNCriteria.h
=> 2246 all failing criteria should be added into the failing criteria list fedora and windows fix

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestCriteria.cpp
=> #2246 Fedora Clang fix

.vscode/launch.json, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.h
=> #2385 investigate why the compilation of models is long

README.md
=> #2596 update readme: get involved section

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py
=> #2560 fix f(g(...), h(...)) case

README.md
=> #2600 add openSSF badge

dynawo/sources/Modeler/DataInterface/DYNGeneratorInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/test/TestCriteria.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestBatteryInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestGeneratorInterface.cpp
reactive power over the full diagram
closes #2586
=> #2586 add a method in generator interface to compute the maximum

dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.h, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py
calculated variables
closes #2581
=> #2581 Do not transform variable from a table with dynamic indexing into

dynawo/3rdParty/libiidm/patch/common/libiidm.patch
=> #2602 Fix powsybl-iidm4cpp xml export on Windows.

dynawo/sources/API/CRV/CRVCsvExporter.cpp, dynawo/sources/API/CRV/test/TestExporters.cpp, dynawo/sources/Simulation/DYNSimulation.h, nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLine/IEEE14.fsv, nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLine/reference/outputs/finalStateValues/finalStateValues.xml
=> #2594 No dump of FSV-only data in the .csv file

dynawo/3rdParty/libiidm/patch/common/libiidm.patch
=> 2602 fix libiidm windows v13

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/DiscretePI.extvar, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/DiscretePI.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/DiscretePI.xml
=> 2614 discrete pi model

dynawo/sources/Modeler/DataInterface/DYNGeneratorInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/IIDM/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestBatteryInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestGeneratorInterface.cpp
=> #2605 add an interface in generator iidm api to collect the energy

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py
=> #2560 fix f(..., g(..., h(..))) case.... Hopefully this is the final fix

dynawo/sources/Launcher/dynawo.cmd.in
=> #2578 Fix dynawo.cmd for local use.

nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/globalInit/dumpInitValues-GEN____2_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/globalInit/dumpInitValues-GEN____3_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/globalInit/dumpInitValues-GEN____6_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/globalInit/dumpInitValues-GEN____8_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/localInit/dumpInitValues-GEN____1_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/localInit/dumpInitValues-GEN____2_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/localInit/dumpInitValues-GEN____3_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/localInit/dumpInitValues-GEN____6_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_NonDefaultLocalInitParams/reference/outputs/initValues/localInit/dumpInitValues-GEN____8_SM.txt
=> #2304 Update nrt reference

.github/workflows/nightly-release-windows.yml
=> #2655 Workflow to build dynawo on Windows nightly.

.github/workflows/nightly-release-windows.yml
=> #2655 Fix directory not existing.

.github/workflows/nightly-release-windows.yml
=> #2655 Fix checkout.

.github/workflows/nightly-release-windows.yml
=> #2655 Debug upload for windows release.

.github/workflows/nightly-release-windows.yml
=> #2655 Try to fix upload of big assets.

.github/workflows/nightly-release-windows.yml
=> #2655 Change url for upload.

.github/workflows/nightly-release-windows.yml
=> #2655 Add back change of directory for uploads.

README.md, dynawo/3rdParty/CMakeLists.txt
=> #2641 fix OpenModelica compiler build on Windows

.github/workflows/nightly-release-windows.yml
=> #2655 Debug upload failing.

.github/workflows/nightly-release-windows.yml
=> #2655 Put back 3rd parties.

.github/workflows/nightly-release-windows.yml
=> #2655 Put back Dynawo build.

.github/workflows/nightly-release-windows.yml
=> #2655 Try to fix curl.

dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.h, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_DynSilentZ.cpp
=> #2619 fix multi switch

.github/workflows/nightly-release-windows.yml
=> #2655 Clean debug and better handle of version number.

util/warnings_to_filter.txt
=> #2636 update warnings_to_filter.txt

dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h
=> #2576 fix doxygen

dynawo/3rdParty/libiidm/patch/common/libiidm.patch
=> #2602 Fix windows xml export.

dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h
=> #2576 fix fedora build

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/Standard/PSS2A.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/ElectricalControlWind.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/ACVoltageControl/QRefLim.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/ACVoltageControl/QRefQU.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/ActivePowerControl/BaseActivePowerControl.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/ActivePowerControl/DeltaP.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/DCVoltageControl/BaseDCVoltageControl.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/PIAntiWindup.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimitedFirstOrder.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimitedLeadLag.mo
closes [#2706 ](https://github.com/dynawo/dynawo/issues/2706)
=> #2706 limitsAtInit removed

util/nrt_diff/settings.py
=> #2710 also compare json results files

.github/workflows/nightly-release.yml, .github/workflows/release.yml, .github/workflows/tools.sh
=> #2714 Fix workflow curl calls and add token.

.github/workflows/nightly-release.yml, .github/workflows/release.yml, .github/workflows/tools.sh
=> 2714 fix workflow v14

.github/workflows/nightly-release-windows.yml, .github/workflows/nightly-release.yml
=> 2308 nightly release v1.4

.github/workflows/nightly-release.yml
=> #2308 Fix name of release.

dynawo/sources/API/CRV/test/TestExporters.cpp, dynawo/sources/Modeler/Common/DYNSubModel.h, dynawo/sources/Modeler/DataInterface/DYNCriteria.cpp, dynawo/sources/Modeler/DataInterface/DYNCriteria.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestCriteria.cpp
=> 2535 criteria when no voltage level is defined in power criteria then all loads should be added by default

dynawo/sources/Common/DYNFileSystemUtils.cpp, dynawo/sources/Common/DYNIoDico.cpp, util/windows/deploy.cmd
=> #2670 fix incomplete deployment and path separator on windows

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPV.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPVDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPVDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPV_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/GeneratorPVDiagramPQ.xml, util/xsl/695.par.xsl
This PR:
- fixes the LambdaPuSNom calculation in GeneratorPV model
- improves the coding style of the model
- adds a model with a PQ diagram
The linked dynawo-rte and dynawo-interface PR are done as well.
=> #2704 DynaWaltz : Fix and improve GeneratorPV

dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/IEC/BaseConverters/GenSystem4.mo
=> #2745 Correct FOCB (IEC WT)

README.md, documentation/README.md, documentation/installation/installation.tex, documentation/introduction/introduction.tex
=> #2747 update documentation links to v1.4.0 assets

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
=> #2734 Increase maximum number of connection of VRRemote

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPV.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPV.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPVDiagramPQ.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorPVDiagramPQ.mo
=> #2755 Add deltaPmRefPu and deltaURefPu for GeneratorPV

dynawo/sources/Modeler/DataInterface/DYNThreeWTransformerInterface.h, dynawo/sources/Modeler/DataInterface/DYNTwoWTransformerInterface.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNThreeWTransformerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/IIDM/DYNTwoWTransformerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNFictTwoWTransformerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNFictTwoWTransformerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNThreeWTransformerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNThreeWTransformerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNTwoWTransformerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNTwoWTransformerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestFictTwoWTransformerInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestThreeWTransformerInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestTwoWTransformerInterface.cpp
=> #2756 add iidm active season extension to transformers

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/IntegratorVariableLimits.mo
@ErwanGuichard49 you can pull this branch, improve the model and do the modifications on the VRJiren test case on dynawo-rte
=> #2389 Improve IntegratorVariableLimits

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py
=> #2783 read all init files (06/08) generated by OM

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py
=> #2758 better handle of embedded if  a - (if ... b else c) = 0

dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Grid/FullDynamicModel.mo
=> #2717 g20 moved on diagram

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/SecondaryVoltageControl/Simplified/SecondaryVoltageControl.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
=> #2791 add a parameter to initialize the frozen variable of the VRRemote

dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVTfo.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVTfoDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVTfoDiagramPQ_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVTfo_INIT.mo, nrt/data/DynaFlow/GeneratorPVTfo/GeneratorPVTfo.par
=> #2804 DynaFlow : simplify GeneratorPVTfo Tfo representation

util/curvesToHtml/csvToHtml/csvToHtml.py, util/curvesToHtml/xmlToHtml/xmlToHtml.py
=> #2812 handle '+' character in curves plot

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/DiscretePI.extvar, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/DiscretePI.mo
=> #2801 switch discrete pi

dynawo/sources/Models/CPP/Controls/Voltage/ModelVoltageMeasurementsUtilities/DYNModelVoltageMeasurementsUtilities.cpp, dynawo/sources/Models/CPP/Controls/Voltage/ModelVoltageMeasurementsUtilities/DYNModelVoltageMeasurementsUtilities.h, dynawo/sources/Models/CPP/Controls/Voltage/ModelVoltageMeasurementsUtilities/test/TestModelVoltageMeasurementsUtilities.cpp, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/PIAntiWindUpTable.mo
=> #2799 Export min and max index on VMU model and adapts PITable's parameters

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/IEC/BaseControls/WT/QControl.mo
=> #2831 IEC WT MultiSwitch correction

util/windows/deploy.cmd
=> #2834 deploy xmllint on windows

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/PIAntiWindUpTable.mo
=> #2839 Fix PIAntiWindUpTable

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNThreeWTransformerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNTwoWTransformerInterfaceIIDM.h, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/scriptVarExt.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py, dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.h
=> #51 fix latest sonar issues

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNThreeWTransformerInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNTwoWTransformerInterfaceIIDM.h
=> #541 fix doxygen

dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.h
=> #51 fix doxygen

.gitignore, dynawo/sources/API/JOB/CMakeLists.txt, dynawo/sources/API/JOB/JOBInitialStateEntryFactory.cpp, dynawo/sources/API/JOB/JOBInitialStateEntryFactory.h
=> #2690 Add initial state entry factory in jobs

dynawo/3rdParty/libiidm/libiidm.cmake
=> #2857 fix missing IIDM imported libs in Windows distribution

dynawo/sources/Modeler/ModelManager/DYNModelicaOverridenFunctions.cpp
=> #2836 fix clang compilation

dynawo/sources/Modeler/DataInterface/DYNCriteria.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestCriteria.cpp
=> 2848 do not test fictitious sources in criteria

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/ReactivePowerControlLoops/ReactivePowerControlLoop.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/ReactivePowerControlLoops/ReactivePowerControlLoop2.mo, nrt/data/DynaFlow/GeneratorPVTfo/GeneratorPVTfo.crv, nrt/data/DynaFlow/GeneratorPVTfo/GeneratorPVTfo.par
=> #2856 added UStatorRefMaxPu and UStatorMinPu in RPCL

dynawo/sources/Modeler/Common/DYNDynamicData.cpp
=> #2810 Clang fix

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp
=> #2876 Fix p0ACEmulation in DYNHvdcLineInterfaceIIDM v1.5

dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulationVariableK.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulationVariableK.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulationVariableK_INIT.mo
=> #2887 Make K an optional extvar in ACEmulationVariableK

util/nrt_diff/nrtDiff.py
=> #2833 fix nrt diff for finalValues files

README.md, documentation/README.md, documentation/installation/installation.tex, documentation/introduction/introduction.tex
=> #2896 update links in readme and documentation for release v1.4.1

dynawo/sources/Modeler/DataInterface/DYNCriteria.cpp, dynawo/sources/Modeler/DataInterface/DYNCriteria.h, dynawo/sources/Modeler/DataInterface/DYNGeneratorInterface.h, dynawo/sources/Modeler/DataInterface/DYNLoadInterface.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.h, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLoadInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLoadInterfaceIIDM.h
=> #2913 Fix sources criteria

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Events/Event.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/CoordinatedVControl.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/CoordinatedVControl_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/Diagram.txt, dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/package.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/package.order, dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/package.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/package.order, dynawo/sources/Models/Modelica/Dynawo/Examples/package.order
=> #2892 Added a generator test case model in Dynawo Examples

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, nrt/data/DynaFlow/GeneratorPVTfo/GeneratorPVTfo.par, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/globalInit/dumpInitValues-_GEN____1_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/globalInit/dumpInitValues-_GEN____2_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/globalInit/dumpInitValues-_GEN____3_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/globalInit/dumpInitValues-_GEN____6_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/globalInit/dumpInitValues-_GEN____8_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/localInit/dumpInitValues-_GEN____1_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/localInit/dumpInitValues-_GEN____2_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/localInit/dumpInitValues-_GEN____3_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/localInit/dumpInitValues-_GEN____6_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroParameterSet/reference/outputs/initValues/localInit/dumpInitValues-_GEN____8_SM.txt
=> #2559 Tables from Modelica models have c++ style indexes (from 0->N-1)

.github/workflows/nightly-release-windows.yml
=> #2903 update Dynawo Windows reference version

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Hydraulic/HYGOV.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/IEEEG1.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/Standard/PssIEEE2B.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/ExcIEEEAC1A.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/IEEET1.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/MAXEX2.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/SCRX.extvar, nrt/data/SMIB/Standard/TestCase2ST4B/TestCase2ST4B.dyd, nrt/data/SMIB/Standard/TestCase2ST4B/TestCase2ST4B.par
=> #2918 Optional variables, constant omegaRef for TestCase2

.github/workflows/nightly-release.yml
=> #2949 fix nrt in nightly windows

.github/workflows/ci.yml, dynawo/sources/Models/Modelica/PreassembledModels/CMakeListsModelsTargets.txt
=> #2947 add Step dependency to SMIB_MODELS

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNFictTwoWTransformerInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestDataInterface.cpp
=> #2927 Fix for 3W transformers and ration tap changers.

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/DiscreteIntegrator.extvar, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/DiscreteIntegrator.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/DiscreteIntegrator.xml
=> 2954 adapt discrete pi

.github/workflows/ci.yml
=> #2958 run NRT on demand in CI

.gitignore, examples/DynaWaltz/description/DynaWaltzExamples.tex, nrt/data/IEEE14/IEEE14_WithAutomata/description/IEEE14_WithAutomata.tex, nrt/data/SMIB/SMIB_BasicTestCases/description/SMIB.tex
=> #2931 correct nrt descriptions that were no longer compiling

README.md
=> #2882 Add link to nightly documentation in README

dynawo/sources/Models/CMakeLists.txt
=> #2975 Add OPENMODELICAHOME to work with an distribution of OpenModelica.

dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.h
=> #2907 fix doxygen

dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.cpp
=> #2907 fix debug build

util/xsl/2172.par.xsl
=> #2172 Update HVDC parameters automatically

.github/release.js, .github/workflows/nightly-release.yml
=> #2951 replace action with javascript

dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSCDanglingP.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSCDanglingUdc.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/HVDC.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Photovoltaics/WECC/PVCurrentSource.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Photovoltaics/WECC/PVVoltageSource.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WT4ACurrentSource.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WT4BCurrentSource.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WTG4ACurrentSource.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WTG4BCurrentSource.mo
=> #2172 Filled PLL parameters on WT Modelica examples

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBusInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCalculatedBusInterfaceIIDM.cpp, dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/Bus.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBus.mo, dynawo/sources/Models/Modelica/PreassembledModels/CMakeListsModelsTargets.txt, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm/reference/outputs/initValues/globalInit/dumpInitValues-busInf.txt, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.dyd, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.par, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/curves.crv, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/globalInit/dumpInitValues-bus1.txt, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/globalInit/dumpInitValues-bus2.txt, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/globalInit/dumpInitValues-busInf.txt, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/localInit/dumpInitValues-bus1.txt, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/localInit/dumpInitValues-bus2.txt, nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/localInit/dumpInitValues-busInf.txt
=> #2973 Add U from UPu for InfiniteBus and Bus.

.github/workflows/nightly.yml
=> #3013 Start nightlies after nightly-releases

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/IEEET1.mo
=> Fix IEEET1 initialisation for Ke not 0

dynawo/sources/Common/Dictionaries/DYNError_en_GB.dic, dynawo/sources/Modeler/Common/DYNModel.h, dynawo/sources/Modeler/Common/DYNModelMulti.cpp, dynawo/sources/Modeler/Common/DYNModelMulti.h, dynawo/sources/Modeler/Common/DYNSubModel.h, dynawo/sources/Modeler/ModelManager/DYNModelManager.h, dynawo/sources/Modeler/ModelManager/DYNModelModelica.h, dynawo/sources/Modeler/ModelManager/test/Test.cpp, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.h, dynawo/sources/Solvers/Common/DYNSolverImpl.h
=> #3001 Display an info log if z is NaN

.github/release.js, .github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #3016 enhance published release

.github/workflows/nightly.yml
=> Fix ubuntu nightly nrt.

util/curvesToHtml/csvToHtml/csvToHtml.py, util/curvesToHtml/xmlToHtml/xmlToHtml.py
=> #3008 jobs-with-curves: handle the case in which a model name starts

README.md
=> #3066 Added Julien De Sloovere on the Readme page

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Generic/GenericAutomaton.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Generic/GenericAutomatonConstants.mo
=> #2291 revert unwanted change

util/updateXML/update1.5.1.0.py, util/updateXML/update1.6.0.0.py
=> #1581 first update scripts for v1.5.1 and v1.6.0

dynawo/cmake/FindSundials.cmake
=> 2291 SUNDIALS compilation fix

util/updateXML/content/Ticket.py, util/updateXML/content/sources/Dyd/DydData.py, util/updateXML/content/sources/Job/Jobs.py, util/updateXML/content/sources/utils/Common.py, util/updateXML/content/test/TestDyd/TestDyd/TestDyd.py, util/updateXML/content/test/TestJob/TestJob/TestJob.py, util/updateXML/content/test/TestTicket/TestTicket.py, util/updateXML/content/test/TestTicket/res/select_tickets/inputs/fic_DYD.xml, util/updateXML/content/test/TestTicket/res/select_tickets/inputs/fic_JOB.xml, util/updateXML/content/test/TestTicket/res/select_tickets/inputs/fic_PAR.xml, util/updateXML/content/test/TestTicket/res/select_tickets/inputs/solvers.par, util/updateXML/content/test/TestTicket/res/select_tickets/reference/fic_DYD.xml, util/updateXML/content/test/TestTicket/res/select_tickets/reference/fic_JOB.xml, util/updateXML/content/test/TestTicket/res/select_tickets/reference/fic_PAR.xml, util/updateXML/content/test/TestTicket/res/select_tickets/reference/solvers.par, util/updateXML/content/test/TestTicket/res/select_tickets/select_tickets.py, util/updateXML/content/test/TestTicket/res/select_tickets/select_tickets1.4.0.0.py, util/updateXML/content/test/TestTicket/res/select_tickets/select_tickets1.4.0.1.py, util/updateXML/content/test/TestTicket/res/select_tickets/select_tickets1.4.0.2.py, util/updateXML/content/test/TestTicket/res/select_tickets/select_tickets1.4.0.3.py, util/updateXML/content/test/TestTicket/res/select_tickets/select_tickets1.4.0.4.py, util/updateXML/content/test/TestTicket/res/select_tickets/select_tickets1.4.0.5.py, util/updateXML/content/test/test.py, util/updateXML/content/updateDynawoNRT/updateDynawoNRT.py
=> 3080 add the possibility to apply a specific sublist of updates

util/envDynawo.sh, util/updateXML/content/updateDynawoNRT/updateDynawoNRT.py
=> #3089 Add --scriptfolders option for updateDynawoNRT.py and updateXML folder to deploy

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
(sqrt(min(..., max(..., if(...)))))
=> #3097 better handle of complex conditional equations (if noEvent

dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic, dynawo/sources/Common/Dictionaries/DYNTimeline_oppositeEvents.dic, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/SecondaryVoltageControl/Simplified/SecondaryVoltageControl.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQProp.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDangling.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDanglingDiagramPQ.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDiagramPQ.mo, dynawo/sources/Simulation/DYNSimulation.cpp, nrt/data/DynaFlow/GeneratorPVTfo/reference/outputs/timeLine/timeline.xml, nrt/data/DynaFlow/GeneratorPVTfoRpclTimeline/reference/outputs/timeLine/timeline.xml, nrt/data/DynaFlow/VRRemote/reference/outputs/timeLine/timeline.xml
=> #3065 properly set limUQUp/Down when the hvdc is not regulating

dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.cpp
=> #3060 Fix on dump start for OmegaRef.

dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
=> #3101 fix Q2 element for two windings transformer element

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestDataInterface.cpp
=> #3049 Avoid dumping 0 instead of undefined values for HVDC power values when applicable

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestDataInterface.cpp
=> 3049 Assign NaN if either HVDC P or Q equals 0

dynawo/sources/Common/Dictionaries/DYNError_en_GB.dic, dynawo/sources/Simulation/DYNSimulation.cpp
=> #3033 add MissingParFile error message

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Governor_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/Pss_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/package.order, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Exciter_INIT.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/package.order
=> #3091 New initialization models

dynawo/sources/API/LEQ/LEQLostEquipmentsCollection.h
=> #3153 Doxygen fix

dynawo/sources/Models/Modelica/Dynawo/package.mo
=> #3160 Update annotation version to 1.6.0

util/warnings_to_filter.txt
=> #2455 Doxygen fix

dynawo/sources/Modeler/DataInterface/DYNCurrentLimits.h
=> #2455 Fedora fix

util/warnings_to_filter.txt
=> #2455 Centos Doxygen fix

dynawo/sources/Common/DYNError.h, dynawo/sources/Common/DYNErrorQueue.h, dynawo/sources/Common/DYNMessage.h, dynawo/sources/Common/DYNMessageTimeline.h, dynawo/sources/Common/DYNParameter.cpp, dynawo/sources/Common/DYNParameter.h, dynawo/sources/Common/DYNTerminate.h, dynawo/sources/Common/DYNTimer.cpp, dynawo/sources/Common/DYNTimer.h, dynawo/sources/Common/DYNTrace.cpp, dynawo/sources/Common/DYNTrace.h, dynawo/sources/Common/DYNTraceStream.cpp, dynawo/sources/Common/DYNTraceStream.h, dynawo/sources/Common/test/TestParameter.cpp, dynawo/sources/Simulation/DYNSimulation.cpp, dynawo/sources/Simulation/DYNSimulation.h, dynawo/sources/Simulation/DYNSimulationContext.cpp, dynawo/sources/Simulation/DYNSimulationContext.h, dynawo/sources/Solvers/AlgebraicSolvers/test/TestBasics.cpp, dynawo/sources/Solvers/Common/DYNSolver.h, dynawo/sources/Solvers/Common/DYNSolverFactory.cpp, dynawo/sources/Solvers/Common/DYNSolverFactory.h, dynawo/sources/Solvers/Common/DYNSolverImpl.cpp, dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.h, dynawo/sources/Solvers/VariableTimeStep/SolverIDA/DYNSolverIDA.cpp, dynawo/sources/Solvers/VariableTimeStep/SolverIDA/DYNSolverIDA.h, dynawo/sources/Test/initXml.cpp
=> #3128 Delete explicit destructors in Common, Simulation and Solvers source folders

util/updateXML/content/sources/Dyd/Connects.py, util/updateXML/content/sources/Dyd/ModelTemplate.py, util/updateXML/content/sources/Dyd/ModelicaModel.py, util/updateXML/content/sources/utils/Common.py, util/updateXML/content/sources/utils/UpdateXMLExceptions.py, util/updateXML/content/test/TestDyd/TestBBM/TestBBM.py, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/add_connect.py, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/add_connect1.4.0.0.py, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/inputs/fic_DYD.xml, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/inputs/fic_JOB.xml, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/inputs/fic_PAR.xml, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/inputs/solvers.par, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/reference/fic_DYD.xml, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/reference/fic_JOB.xml, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/reference/fic_PAR.xml, util/updateXML/content/test/TestDyd/TestBBM/res/add_connect/reference/solvers.par, util/updateXML/content/test/TestDyd/TestModelicaModel/TestModelicaModel.py, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/add_unit_dynamic_model_connect.py, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/add_unit_dynamic_model_connect1.4.0.0.py, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/inputs/fic_DYD.xml, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/inputs/fic_JOB.xml, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/inputs/fic_PAR.xml, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/inputs/solvers.par, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/reference/fic_DYD.xml, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/reference/fic_JOB.xml, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/reference/fic_PAR.xml, util/updateXML/content/test/TestDyd/TestModelicaModel/res/add_unit_dynamic_model_connect/reference/solvers.par
=> #3196 Add a facility to add a connect in a Dyd file

util/updateXML/content/sources/Job/JobData.py, util/updateXML/content/sources/Job/Jobs.py
=> #3200 fix the bug when parsing XML comments in updateXML

util/updateXML/content/sources/Job/Jobs.py, util/updateXML/content/test/TestDyd/TestDyd/TestDyd.py, util/updateXML/content/test/TestTicket/TestTicket.py, util/updateXML/content/test/utils.py
=> #3203 Add an option to condition the addition of dynawo version in updated XML files in updateXML

util/updateXML/content/sources/Dyd/Connects.py, util/updateXML/content/sources/Dyd/DydData.py, util/updateXML/content/sources/Job/Jobs.py, util/updateXML/content/updateDynawoNRT/updateDynawoNRT.py
=> #3198 Change the replacement facility of updateXML

README.md, documentation/README.md, documentation/installation/installation.tex, documentation/introduction/introduction.tex
=> #3233 updates links following v1.6.0

dynawo/sources/Modeler/Common/DYNModelUtil.h
=> #3059 Fix doxygen.

.github/workflows/ci.yml
=> #3240 Fix doxygen deploy.

.github/workflows/ci.yml
=> #3240 Fix doxygen deploy 2.

.github/workflows/ci.yml
=> #3240 Fix doxygen deploy 3.

dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/package.order
=> #3251 Add LoadAlphaBetaRestorativeNetwork to package order

dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h, dynawo/sources/Modeler/Common/DYNConnectorCalculatedVariable.h, dynawo/sources/Modeler/Common/DYNSubModel.h, dynawo/sources/Modeler/ModelManager/DYNModelManager.h
=> #3256 Fix doxygen.

documentation/configuringDynawo/DynawoInputFiles.tex, dynawo/sources/API/JOB/JOBXmlHandler.cpp, dynawo/sources/API/JOB/test/TestXmlImporter.cpp, dynawo/sources/API/JOB/xsd/jobs.xsd
=> #3213 jobs: dumpInitValues global and local attributes optional

dynawo/sources/Modeler/Common/DYNModelMulti.cpp
=> #3059 fix X variable header in VARIABLES log file

dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.cpp
=> #2190 Fix prediction for SolverSIM.

.gitignore, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Simplified/GoverNordic.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Hydraulic/HYGOV1.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Hydraulic/HyGov.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/Power.mo
closes [#3151](https://github.com/dynawo/dynawo/issues/3151)
=> #3151 Power with an option for negative input values

dynawo/sources/Models/Modelica/Dynawo/Resources/Include/logEvent.h
closes [#3210 ](https://github.com/dynawo/dynawo/issues/3210)
=> #3210 Nb of arguments of logEvent corrected

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/IqInjectionLogic.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/ElectricalControlWind.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Wind/WECC/BaseClasses/BaseWT4.mo
=> #3237 Modify HoldIq sign convention according to the norm

dynawo/sources/Modeler/DataInterface/CMakeLists.txt, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/CMakeLists.txt
=> #3283 Install missing headers for dependents projects.

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
=> #3317 Update actions checkout to v4.

.vscode/settings.json
=> #3311 Add OPENMODELICAHOME in vscode settings

dynawo/sources/Models/CPP/Common/DYNModelCPP.h, dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.h, dynawo/sources/Models/CPP/Controls/Shunts/ModelCentralizedShuntsSectionControl/DYNModelCentralizedShuntsSectionControl.h, dynawo/sources/Models/CPP/Controls/Voltage/ModelVoltageMeasurementsUtilities/DYNModelVoltageMeasurementsUtilities.h, dynawo/sources/Models/CPP/Events/ModelAreaShedding/DYNModelAreaShedding.h, dynawo/sources/Models/CPP/Events/ModelVariationArea/DYNModelVariationArea.h, dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/DYNModelVoltageSetPointChange.h, dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.h
=> #3275 Fix clang warnings.

.github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #3313 Add new gcc11 distribution.

.github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
=> #3326 Fix node20 issues with old OS.

dynawo/sources/Modeler/DataInterface/test/TestDataInterface.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp
=> #3288 revert

.github/workflows/nightly-release.yml
=> #3313 Add python3 as environment variable for gcc11 workflow.

.github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #3313 Fix bash syntax in workflow.

.github/workflows/ci.yml
=> #3349 Add small distrib master to use it in CI for child projects.

.github/workflows/nightly-1.yml, .github/workflows/nightly-2.yml
=> #3347 Split nightly in two.

.github/workflows/ci.yml
=> #3349 Add missing environment variables.

.github/workflows/nightly-2.yml, .github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #3361 Update CI to handle nodeJS 20 in old OS.

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #3361 Update for nodeJs 20.

util/envDynawo.sh
=> #3359 Fix missing option in envDynawo.

.github/workflows/ci.yml
=> #3370 Fix master build in ci.

dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp
=> #3384 properly add G equations for delays in EQUATIONS log file

util/warnings_to_filter.txt
=> #3244 Doxygen fix

util/warnings_to_filter.txt
=> #3244 Doxygen fix 2

util/nrt_diff/constraintsDiff.py, util/nrt_diff/diffUtils.py, util/nrt_diff/finalStateValuesDiff.py, util/nrt_diff/iidmDiff.py
=> #3418 add relative tolerance in diff sripts for nrt

examples/DynaSwing/IEC/Wind/Neplan/WPP4BCurrentSource2015Q/WPP4BCurrentSource2015.par, util/updateXML/update1.7.0.0.py, util/updateXML/update1.7.0.4.py
=> #3373 modify solver parameters in 1 testcase so that it is more robust

util/nrt_diff/constraintsDiff.py, util/nrt_diff/finalStateValuesDiff.py, util/nrt_diff/iidmDiff.py
=> #3418 add line previously erased by mistake

documentation/resources/dynawoDocumentation.bib
=> #3281 fix bibtex

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/Standard/PssKundur.extvar
closes [#3455](https://github.com/dynawo/dynawo/issues/3455)
=> #3455 omegaRefPu as optional input of PssKundur

dynawo/sources/Models/Modelica/Dynawo/Examples/IllustrativeExamples/DynaFlow/CoordinatedVControl.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/RVS/Grid/FullStatic.mo
=> #3395 Update VRRemote parameters to pu in Modelica example

util/warnings_to_filter.txt
=> #3465 Fix doxygen

NOTICE.md
=> #3467 add a NOTICE.md file to better specify licenses

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/BaseClasses/BasePulse.mo
Ensures a steady initialization if u(t = 0) = true.
closes [#3441](https://github.com/dynawo/dynawo/issues/3441)
=> #3441 tTrigger reset if u changes

.github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #3438 workflows fix

dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/BaseClasses/BasePVCurrentSource.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/BaseClasses/BasePVVoltageSource.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/BaseClasses/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/BaseClasses/package.order, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVCurrentSourceB.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVCurrentSourceBNoPlantControl.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVCurrentSourceBNoPlantControl.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVVoltageSourceANoPlantControl.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVVoltageSourceANoPlantControl.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVVoltageSourceB.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVVoltageSourceBNoPlantControl.extvar, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVVoltageSourceBNoPlantControl.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/package.order, dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt, dynawo/sources/Models/Modelica/PreassembledModels/PhotovoltaicsWeccCurrentSourceBNoPlantControl.xml, dynawo/sources/Models/Modelica/PreassembledModels/PhotovoltaicsWeccVoltageSourceANoPlantControl.xml, dynawo/sources/Models/Modelica/PreassembledModels/PhotovoltaicsWeccVoltageSourceBNoPlantControl.xml
=> #3460 Add WECC PV models without plant control

dynawo/sources/Common/DYNGraph.cpp, dynawo/sources/Common/DYNGraph.h, dynawo/sources/Modeler/Common/DYNModelMulti.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.cpp
loop when 2 switches are connected to the same calculated buses
closes #3494
=> #3494 properly identify edges in node breaker graph to avoid an infinite

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCalculatedBusInterfaceIIDM.cpp
buses that can't be re-read
closes #3464
=> #3464 avoid having very small values dumped in the iidm for calculated

examples/DynaSwing/IEC/Wind/Neplan/WPP4BCurrentSource2015Q/WPP4BCurrentSource2015.par
- [x unit tests and non-regression tests were added (new model, new feature and bug fix)
=> #3513 reduce minimalAcceptableStep

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #3526 Windows workflows fix

dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.h
them in the init model values
closes #3529
=> #3529 properly define init variable of network model to be able to dump

dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimitedDivision.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/package.order
closes [#3507 ](https://github.com/dynawo/dynawo/issues/3507)
=> #3507 New LimitedDivision block

dynawo/sources/Simulation/DYNSimulation.h
=> #3536 Add getters to retrieve output file names from a simulation

dynawo/sources/API/CSTR/CSTRConstraint.h, dynawo/sources/API/CSTR/CSTRTxtExporter.cpp, dynawo/sources/API/CSTR/CSTRXmlExporter.cpp, dynawo/sources/Common/Dictionaries/DYNConstraint_en_GB.dic, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Current/CurrentLimitAutomaton.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/logConstraintBeginData.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/logConstraintEndData.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/package.order, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/ConstraintKeys.mo, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_CurrentLimitAutomaton/IEEE14.jobs, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_CurrentLimitAutomaton/reference/outputs/constraints/constraints.xml
=> #3544 Add constraints when CLA is arming or opening a line

dynawo/sources/API/CSTR/CSTRConstraint.h, dynawo/sources/API/CSTR/CSTRTxtExporter.cpp, dynawo/sources/API/CSTR/CSTRXmlExporter.cpp, dynawo/sources/API/CSTR/test/TestExporter.cpp, dynawo/sources/Common/Dictionaries/DYNConstraint_en_GB.dic, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.cpp, dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Current/CurrentLimitAutomaton.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/logConstraintBeginData.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/logConstraintEndData.mo, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/package.order, dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/ConstraintKeys.mo, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_CurrentLimitAutomaton/IEEE14.jobs, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_CurrentLimitAutomaton/reference/outputs/constraints/constraints.xml
=> #3544 fix nrt v17

dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic, examples/DynaWaltz/IEEE14/IEEE14_CascadingLineTrippings/reference/outputs/timeLine/timeline.log, examples/DynaWaltz/IEEE14/IEEE14_GeneratorDisconnections/reference/outputs/timeLine/timeline.log, examples/DynaWaltz/IEEE57/IEEE57_GeneratorDisconnection/reference/outputs/timeLine/timeline.log, examples/DynaWaltz/Nordic/reference/outputs/timeLine/timeline.xml, examples/DynaWaltz/NordicTCB/reference/outputs/timeLine/timeline.xml, nrt/data/DynaWaltz/Nordic_DumpLoad/reference/0/outputs/timeLine/timeline.xml, nrt/data/DynaWaltz/Nordic_DumpLoad/reference/1/outputs/timeLine/timeline.xml, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_PhaseShifterI/reference/outputs/timeLine/timeline.log, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_PhaseShifterP/reference/outputs/timeLine/timeline.log, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_PhaseShifterP_Modelica/reference/outputs/timeLine/timeline.log, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/timeLine/timeline.log, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChangerBlocking/reference/outputs/timeLine/timeline.log, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChangerCpp/reference/outputs/timeLine/timeline.log, nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger_Modelica/reference/outputs/timeLine/timeline.log
=> #3555 make tap changing timeline message more clear

dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestFictVoltageLevelInterface.cpp, dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestServiceManagerInterface.cpp
=> #2455 fix unit tests on old versions of compiler

dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/SVarCStandard.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/BaseClasses/BaseSVarCTestCase.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/BaseClasses/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/BaseClasses/package.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/BaseClasses/package.order, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCFaultImp.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCLoadVarQ.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCLoadVarQLarge.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCModeChange.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCStepURef.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/package.order
closes [#3563 ](https://github.com/dynawo/dynawo/issues/3563)
=> #3563 Base model for SVarC test cases

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/dataContainer.py
=> #3498 make sure double equalities are encapsulated in a DYN::isEquals

dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/BaseClasses/BaseWindNeplan.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/BaseClasses/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/BaseClasses/package.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/BaseClasses/package.order, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/CMakeLists.txt, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2015.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020FOCB.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4BCurrentSource2020.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4BCurrentSource2020FOCB.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WT4ACurrentSource2015.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WT4ACurrentSource2015FOCB.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WT4ACurrentSource2020.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WT4ACurrentSource2020FOCB.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WT4BCurrentSource2015.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WT4BCurrentSource2015FOCB.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WT4BCurrentSource2020.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WT4BCurrentSource2020FOCB.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/package.order, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WT4ACurrentSource.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WT4BCurrentSource.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WTG4ACurrentSource.mo, dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WTG4BCurrentSource.mo
closes [#3569](https://github.com/dynawo/dynawo/issues/3569)
=> #3569 Base model for Neplan test cases

util/curvesToHtml/resources/curves.js.in, util/curvesToHtml/resources/placeholder.js
=> #3575 add value tooltip to curves

dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
closes [#3571](https://github.com/dynawo/dynawo/issues/3571)
Successful simulation under OM 1.24.4
=> #3571 25 s simulation, Smoothness = LinearSegments

.github/workflows/ci.yml, .github/workflows/nightly-1.yml, .github/workflows/nightly-2.yml
=> #3116 fix workflows for sensitive nrt

examples/DynaWaltz/description/DynaWaltzExamples.tex, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ModelicaModel/IEEE14.dyd, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ModelicaModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ReferenceToParameterFromAnotherModel/Generators.dyd, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ReferenceToParameterFromAnotherModel/IEEE14.dyd, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ReferenceToParameterFromAnotherModel/IEEE14.jobs, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ReferenceToParameterFromAnotherModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ReferenceToParameterFromAnotherModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____2_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ReferenceToParameterFromAnotherModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____3_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ReferenceToParameterFromAnotherModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____6_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ReferenceToParameterFromAnotherModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____8_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/Generators.dyd, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/IEEE14.dyd, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____2_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____3_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____6_SM.txt, nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____8_SM.txt
=> #1272 Miscellanous fixes forgotten by previous commits

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py, dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.cpp, dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.h
=> #3504 fixes handle of div method

dynawo/sources/Models/CPP/Common/DYNModelCPP.cpp, dynawo/sources/Models/CPP/Common/DYNModelCPP.h, util/warnings_to_filter.txt
=> #3457 fix compilation on Fedora

README.md
=> #3621 Update list of maintainers

dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelGenerator.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelSwitch.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelThreeWindingsTransformer.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelVoltageLevel.h, util/nrt_diff/nrtDiff.py
=> #3626 Fix compilation on Fedora + CLANG in Debug

dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelGenerator.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelSwitch.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelThreeWindingsTransformer.h, dynawo/sources/Models/CPP/ModelNetwork/DYNModelVoltageLevel.h, util/nrt_diff/nrtDiff.py
compararison for python2
closes #3626
=> #3626 more fixes for fedora + clang, adaption of nrtDiff log

dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py
=> #3631 parameters are not initialized in the proper order in initRPar

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/BaseClasses/BaseSt1.mo
closes [#3639](https://github.com/dynawo/dynawo/issues/3639)
=> #3639 St1a : initialization accounting for Ir0Pu

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/BaseClasses/BaseIEEEX.mo
closes [#3643](https://github.com/dynawo/dynawo/issues/3643)
=> #3643 EfdMaxPu added to IEEEX2 and IEEX2A

dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.h
=> #3626 and even more fixes for compilation on fedora + clang debug os

dynawo/sources/Simulation/DYNSimulationRT.cpp, dynawo/sources/Simulation/DYNSimulationRT.h
=> DynawoRT: setPublisher uses csv instead of json format

dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h, dynawo/sources/Modeler/Common/DYNModelMulti.h
=> #3259 Fix wrong doxygen modifications.

dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp, dynawo/sources/Models/CPP/ModelNetwork/DYNModelSwitch.cpp
=> #3670 fix compilation errors

dynawo/sources/Models/CPP/Controls/Voltage/ModelSecondaryVoltageControlSimplified/DYNModelSecondaryVoltageControlSimplified.h
=> #3655 fix Fedora compilation

dynawo/sources/Models/CPP/ModelNetwork/DYNModelVoltageLevel.cpp
=> #3699 make FindClosestBBS return the node itself if it is a BBS

dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriVoltageControl.mo, dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REEC/BaseClasses/BaseREEC.mo
=> #3682 Replace Modelica variable limits blocks with the Dynawo block when limits can be equal to 0

dynawo/sources/API/CRV/CRVCurve.cpp, dynawo/sources/API/CRV/CRVCurve.h, dynawo/sources/Modeler/Common/DYNModel.h, dynawo/sources/Modeler/Common/DYNModelMulti.cpp, dynawo/sources/Modeler/Common/DYNModelMulti.h, dynawo/sources/Modeler/Common/DYNSubModel.cpp, dynawo/sources/Modeler/Common/DYNSubModel.h, dynawo/sources/Simulation/DYNSimulation.cpp
=> #3663 calculated var curve optimization

util/updateXML/content/sources/Job/Jobs.py
=> #3810 Fix updateXML when job is without network.

dynawo/sources/Simulation/DYNSimulation.cpp, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINAlgRestoration.cpp, dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINEuler.cpp
=> #3815 quick and dirty fix to display residuals values in debug log

.github/workflows/nightly-2.yml
=> #3624 increase tolerance in nightly for numerically non stable test
